UPBGE/upbge

- doc/python_api/rst/bge_types/bge.types.KX_WorldInfo.rst
- source/gameengine/Ketsji/KX_WorldInfo.cpp
- source/gameengine/Ketsji/KX_WorldInfo.h
This answers request: https://github.com/UPBGE/blender/issues/452
test file: http://pasteall.org/blend/index.php?id=46581
> UPBGE: Add read only API for use envlight and envlight color

- source/gameengine/Ketsji/KX_GameObject.cpp
A check of prop.size() == 0 was rewritten in prop.size() instead of prop.empty().
In the same time the function CheckRayCastObject is implemented to factorise the
proprety and mask check made in RayHit and NeedRayCast.
CheckRayCastObject also add a little optimization by not getting the object collision
group when the mask accept all objects.
Fix #671.
> UPBGE: Fix ray cast with xray and property filtering.

- intern/ghost/intern/GHOST_SystemPathsCocoa.mm
- intern/ghost/intern/GHOST_SystemPathsUnix.cpp
- intern/ghost/intern/GHOST_SystemPathsWin32.cpp
Changed `GHOST_SystemPaths::getSystemDir` and
`GHOST_SystemPaths::getUserDir` implementations to use UPBGE specific
folders.
Fix #755.
> UPBGE: Change default directories

- build_files/cmake/platform/platform_apple.cmake
- intern/mathfu/mathfu/utilities.h
- intern/mathfu/mathfu/vector.h
related to TBB library detection and not following the std::abs standard
@panzergame are the changes over the mathfu library ok for you?
> UPBGE: Additional fixes to can compile under MacOS X

- source/gameengine/Ketsji/KX_KetsjiEngine.cpp
Previously when the frame time was too fast the function KX_KetsjiEngine::NextFrame
concluded that 0 frames have to be proceeded and done nothing. This function was
called until the elapsed time was suffisent to process a frame.
This approch is naive, robust and precise but introduce an high CPU usage because
of the extra calls to KX_KetsjiEngine::NextFrame setting the CPU to it's maximum.
To avoid this high usage, the elapsed time to the next frame is computed and the
main thread sleep of this time.
> UPBGE: Sleep when frame time is smaller than fixed frame time.

- source/gameengine/Ketsji/KX_MouseActuator.cpp
- source/gameengine/Ketsji/KX_MouseActuator.h
This occurred under certain situation (i.e fps < 30). Now it run at
first time to relocate the mouse only.
> UPBGE: Fix for mouse actuator return value 

- release/scripts/startup/bl_ui/space_view3d.py
- source/blender/editors/space_view3d/drawobject.c
- source/blender/makesrna/intern/rna_userdef.c
> UPBGE: Expose vertex indices checkbox by default under "N" lateral panel

- source/gameengine/GamePlayer/GPG_ghost.cpp
Blenderplayer now supports backtrace write into text file of the
name of the current loaded file or default "blender".
This file contain the backtrace constructed during a SIGSEGV.
Useful for bug report.
GPG_ghost.cpp mimic creator part by setting up a signal function
sigHandleCrash (or windowsExceptionHandler for windows which call
sigHandleCrash at the end) calling sigHandleCrashBacktrace
in responsible of writing the file using BLI_system_backtrace.
Fix issue: #739.
> UPBGE: Support backtrace file writing for blenderplayer.

- source/gameengine/Ketsji/KX_GameObject.cpp
UPBGE: Fix compound child remove parent
previously the fix before worked for the test case but not for my game
youle pointed out something that worked for both
edit *corner case was remove parent -> set parent in same frame
> fix compound child remove parent try2

- source/gameengine/Ketsji/BL_Action.cpp
This is experimental code as most of code in BL_Action::Update
Similar stuff can be done for shapekeys and many other things
but i have not a precise idea of what the code design should look like
test file: http://pasteall.org/blend/index.php?id=52549
> UPBGE: Add code to play shader nodetree actions

- doc/python_api/rst/bge_types/bge.types.KX_GameObject.rst
- source/blender/draw/intern/DRW_render.h
- source/blender/draw/intern/draw_manager.c
- source/gameengine/Ketsji/KX_GameObject.cpp
- source/gameengine/Ketsji/KX_GameObject.h
- source/gameengine/Ketsji/KX_KetsjiEngine.cpp
- source/gameengine/Ketsji/KX_Scene.cpp
As KX_GameObject is a kindof container for Object, it can be useful to get its Object to perform operations with bpy on it
> UPBGE: Add an API to get KX_GameObject's Object

- source/blender/draw/engines/overlay/overlay_extra.c
> UPBGE: Add code to draw rigid body joints pivot

- source/gameengine/Ketsji/KX_FontObject.cpp
- source/gameengine/Ketsji/KX_GameObject.cpp
- source/gameengine/Ketsji/KX_GameObject.h
- source/gameengine/Ketsji/KX_Scene.cpp
As we didn't find yet the secret of the viewport to have all working without hacking, we hack trying to improve our current hacks.
> UPBGE: Changes in TagForUpdate

- intern/ghost/intern/GHOST_WindowManager.cpp
- source/blender/draw/DRW_engine.h
- source/blender/draw/intern/draw_manager.c
- source/blender/windowmanager/intern/wm_init_exit.c
- source/blender/windowmanager/intern/wm_window.c
- source/gameengine/GamePlayer/GPG_ghost.cpp
- source/gameengine/Ketsji/KX_PythonInit.cpp
- source/gameengine/Ketsji/KX_Scene.cpp
This work is meant to have game actuator restart/load new .blend working, but it is mainly based on experiments.
We commit it anyway waiting for a better solution (which would need to find how to restart game or load a new .blend without spawning a new window)
> UPBGE: Temp fixes for game actuator restart/load .blend

- release/scripts/startup/bl_ui/properties_object.py
- source/blender/makesdna/DNA_collection_types.h
- source/blender/makesrna/intern/rna_collection.c
- source/gameengine/Ketsji/KX_Scene.cpp
A new check is introduced under collection panel in Object tab to can choose between old and new behaviour related to collection/group instantation.
> UPBGE: Add boolean check to allow old collection instantation behaviour

- doc/python_api/rst/bge_types/bge.types.KX_Scene.rst
- source/gameengine/Ketsji/KX_Scene.cpp
- source/gameengine/Ketsji/KX_Scene.h
taking advantage of the previous work on convertBlenderObject function we make
this new function to simplify the loading of all objects inside a
collection.
We will see if we can parallelize the function later.
> UPBGE: Adding python convertBlenderCollection function

- source/blender/python/BPY_extern.h
- source/blender/python/intern/bpy_interface.c
- source/gameengine/Ketsji/KX_PythonInit.cpp
We copy the solution from https://developer.blender.org/
rB79a58eef059ffc3f12d11bd68938cfb1b4cd2462 to solve issues that we have
with Audaspace python
Thanks to @youle31 for find the solution
> UPBGE: Ignore Python user site-packages directory by default

- source/gameengine/Ketsji/BL_Action.cpp
- source/gameengine/Ketsji/KX_GameObject.cpp
- source/gameengine/Ketsji/KX_GameObject.h
This is fixing https://github.com/UPBGE/upbge/issues/1172 but can have a
performances cost
> UPBGE: Fix another issue in parent-children relation transformation

- doc/python_api/rst/bge_types/bge.types.KX_PythonComponent.rst
- source/gameengine/Ketsji/KX_PythonComponent.cpp
- source/gameengine/Ketsji/KX_PythonComponent.h
This is to answer a request from here: https://github.com/UPBGE/upbge/issues/1225
> UPBGE: Add a dispose function called when a component is destroyed

- source/gameengine/Ketsji/KX_PythonInit.cpp
- source/gameengine/Ketsji/KX_PythonInit.h
- source/gameengine/Launcher/LA_Launcher.cpp
- source/gameengine/Launcher/LA_Launcher.h
> UPBGE: Fix audio issue reported by highwaywarrior on discord

- doc/python_api/rst/bge_types/bge.types.KX_GameObject.rst
- source/gameengine/Ketsji/KX_GameObject.cpp
- source/gameengine/Ketsji/KX_GameObject.h
ones)
This is to answer the second part of this request:
https://github.com/UPBGE/upbge/issues/1225
test file: https://pasteall.org/blend/473877dc9df54cf58c2635a89fdaf7f3
> UPBGE: Add onRemove callbacks for KX_GameObject (copied from KX_Scene

- source/blender/blenkernel/intern/python_component.c
- source/blender/python/intern/bpy.c
- source/blender/python/intern/bpy.h
- source/gameengine/Ketsji/KX_PythonInit.cpp
These are the changes that I had to make, in order to build the master branch as an AUR package, using Python 3.8 as a dependency.
I have zero knowledge of C/C++, so it's possible that I did something unreasonable. In that case, please feel free to change it anyway to improve the code.
> Compatibility with Python >= 3.8.x

- source/blender/blenkernel/intern/python_component.c
Again, I don't know much of C/C++, so please feel free to change whatever part that needs to be improved.
(stackoverflow.com is such a wonderful place where you can steal code snippets that you don't really understand to fix your issue :sweat_smile:)
> Fix parsing of KX_PythonComponent names (#1230)

- source/gameengine/Converter/BL_IpoConvert.cpp
- source/gameengine/Ketsji/KX_WorldIpoController.cpp
- source/gameengine/Ketsji/KX_WorldIpoController.h
WorldIpoController was not using the right scene
Using KX_GetActiveScene seems dangerous.
> UPBGE: Fix for update animation in KX_WorldIpoController

- release/scripts/templates_py_components/spaceship.py
Added a "ToyRocket" component as a template useful for quick creation of simple space shooters. Arcade like movement and some basic configurable values. Should be enough for someone new to UPBGE.
> Template for "Simple Space Shooter" component

- source/gameengine/Ketsji/KX_SG_NodeRelationships.cpp
Note:
I picked what was in upbge 0.2.5 and tried to transpose to Moto with the
help of that:
https://math.stackexchange.com/questions/237369/given-this-transformation-matrix-how-do-i-decompose-it-into-translation-rotati
This is to fix
https://github.com/UPBGE/upbge/issues/1291#issuecomment-707280616
my test file is: https://pasteall.org/blend/0d887e6101fc405e9569d6ca480f9967
I didn't tested elsewhere than in this test file for now, and i didn't look how it was in upbge 0.2.5 but it seems something was done in 0.2.5
> UPBGE: Try to fix a weird transformation behaviour with children

- source/gameengine/Ketsji/KX_Camera.cpp
- source/gameengine/Ketsji/KX_KetsjiEngine.cpp
- source/gameengine/Ketsji/KX_Scene.cpp
- source/gameengine/Ketsji/KX_Scene.h
minimap test file: https://pasteall.org/blend/97f46d6903ab42cda589ba552b2b635c
I tested with few files to see if i didn't break something else, but it sounded ok. Few more tests are welcome.
> UPBGE: Restore custom bge viewports

- source/blender/blenkernel/intern/object.c
i do a pull request just to review my changes
> UPBGE: Group bge code in object.c

- source/blender/editors/space_view3d/view3d_view.c
- source/blender/makesdna/DNA_scene_types.h
- source/blender/windowmanager/intern/wm_draw.c
- source/blender/windowmanager/intern/wm_surface.c
- source/blender/windowmanager/wm_surface.h
test file: https://pasteall.org/blend/7d317f4eab18465b8e9d4ca0c3f69dfa
(It is just to not revert
https://github.com/UPBGE/upbge/commit/2dd60e6c2cbdf3e39ed3451ee0f67a5b00a7a5bc
but avoid crash at ge start)
> UPBGE: Fix for XR start in master

- source/gameengine/GamePlayer/GPG_ghost.cpp
it reduce reported mem leaks from 3 to 1
> UPBGE: Try something to reduce leaks count in blenderplayer

- source/gameengine/GamePlayer/GPG_ghost.cpp
- source/gameengine/Ketsji/KX_PythonInit.cpp
- source/gameengine/Ketsji/KX_PythonInit.h
It fixes #1341 on my end but I'm not entirely confident that it doesn't contain any error because I'm not familiar with the language or the environment. So, it'd be advisable to merge this after sufficient code review and testing.
> Fix #1341: Call Py_Initialize() before using Python API

- source/blender/gpu/GPU_shader.h
- source/blender/gpu/intern/gpu_shader.cc
- source/gameengine/Ketsji/KX_Scene.cpp
Issue referenced here: https://github.com/UPBGE/upbge/issues/1354
Thanks very much @lordloki for finding the issue.
I still need to test with other files.
> UPBGE: Try to fix black shading issue

- source/gameengine/Ketsji/BL_Action.cpp
- source/gameengine/Ketsji/BL_Action.h
- source/gameengine/Ketsji/BL_ActionManager.cpp
- source/gameengine/Ketsji/BL_ActionManager.h
It is to fix https://github.com/UPBGE/upbge/issues/1359
I create the pull request, unless lordloki wants to try to recover a big commits series related to IPOs and SG_Controllers...
(I already begun to try this approach in a branch (ipo_cherry) to cherry-pick many commits but i stopped because it seemed too complex to me with my methods to solve conflicts...)
> UPBGE: Try to have IPO actions working as in 0.2.5

- release/scripts/startup/bl_ui/properties_data_light.py
- source/blender/blenkernel/BKE_blender_version.h
- source/blender/blenloader/intern/versioning_upbge.c
- source/blender/draw/engines/eevee/eevee_lights.c
- source/blender/draw/engines/eevee/eevee_private.h
- source/blender/draw/engines/eevee/eevee_shadows_cascade.c
- source/blender/draw/engines/eevee/eevee_shadows_cube.c
- source/blender/draw/engines/eevee/shaders/lights_lib.glsl
- source/blender/makesdna/DNA_light_defaults.h
- source/blender/makesdna/DNA_light_types.h
- source/blender/makesrna/intern/rna_light.c
Based in https://developer.blender.org/D4166 by Alexander Court
Blend example: [test_lights.zip](https://github.com/UPBGE/upbge/files/5746018/test_lights.zip)
> UPBGE: Add "use soft shadow" per light switch

- source/gameengine/Ketsji/BL_Action.cpp
Additionally, refactor world & material code. Now, the 3 nodetrees are
evaluated under the NodeTree code.
Thanks a lot to @youle31 to find the key with Geometry nodes.
Test files:
[Nodes_Action_World.zip](https://github.com/UPBGE/upbge/files/5752530/Nodes_Action_World.zip)
[Nodes_Action_Geometry.zip](https://github.com/UPBGE/upbge/files/5752531/Nodes_Action_Geometry.zip)
[Nodes_Action_Shader.zip](https://github.com/UPBGE/upbge/files/5752532/Nodes_Action_Shader.zip)
[Nodes_Action_World&Shader.zip](https://github.com/UPBGE/upbge/files/5752533/Nodes_Action_World.Shader.zip)
> UPBGE: Add geometry nodes action animation

- doc/python_api/rst/bge.render.rst
- source/blender/blenloader/intern/versioning_upbge.c
- source/blender/editors/space_view3d/view3d_view.c
- source/blender/makesdna/DNA_scene_types.h
- source/blender/makesrna/intern/rna_scene.c
- source/gameengine/Ketsji/KX_PythonInit.cpp
> UPBGE: Clean-up old material related settings

- source/gameengine/Converter/BL_BlenderDataConversion.cpp
- source/gameengine/Ketsji/BL_Action.cpp
- source/gameengine/Ketsji/KX_GameObject.cpp
- source/gameengine/Ketsji/KX_GameObject.h
- source/gameengine/Ketsji/KX_Scene.cpp
- source/gameengine/Ketsji/KX_Scene.h
I had to move some code from KX_GameObject to KX_Scene.
It seems to work but I dooubt it is conventional...
I retried undo but without success
It is to try to fix https://github.com/UPBGE/upbge/issues/1377
Maybe there is a simpler way...
> Try to fix objects obmat at kxscene exit

- release/scripts/startup/bl_ui/properties_render.py
- source/blender/blenkernel/BKE_blender_version.h
- source/blender/blenkernel/intern/scene.c
- source/blender/blenloader/intern/versioning_upbge.c
- source/blender/draw/engines/eevee/eevee_private.h
- source/blender/draw/engines/eevee/eevee_shaders.c
- source/blender/draw/engines/eevee/eevee_smaa.c
- source/blender/draw/engines/eevee/eevee_temporal_sampling.c
- source/blender/draw/engines/eevee/shaders/effect_smaa_frag.glsl
- source/blender/makesdna/DNA_scene_defaults.h
- source/blender/makesdna/DNA_scene_types.h
- source/blender/makesrna/intern/rna_scene.c
After several tests we found these improvements to SMAA:
- Quality presets: Low, Medium, High and Ultra. Default High.
- Internal use of predication for a better edge detection.
> UPBGE: SMAA Quality presets and include predication

- source/gameengine/Converter/BL_BlenderDataConversion.cpp
- source/gameengine/Ketsji/KX_PyConstraintBinding.cpp
- source/gameengine/Physics/Bullet/CcdPhysicsController.cpp
- source/gameengine/Physics/Bullet/CcdPhysicsEnvironment.cpp
- source/gameengine/Physics/Bullet/CcdPhysicsEnvironment.h
- source/gameengine/Physics/Common/PHY_IPhysicsEnvironment.h
- source/gameengine/Physics/Dummy/DummyPhysicsEnvironment.cpp
- source/gameengine/Physics/Dummy/DummyPhysicsEnvironment.h
I'm not sure about what i'm doing.
Blue Print and Wuiaeyo tested with their files and it seemed ok with this second version of the patch.
Sorry to ask you again @lordloki , when you have time (no hurry at all), to test this version with your files (and review if you want).
Thanks to all for the tests!
> UPBGE: Try to fix dupligroups rigid boby constraints replication

- source/blender/windowmanager/intern/wm_init_exit.c
- source/blender/windowmanager/intern/wm_window.c
- source/gameengine/GamePlayer/GPG_Canvas.cpp
- source/gameengine/GamePlayer/GPG_Canvas.h
- source/gameengine/GamePlayer/GPG_ghost.cpp
Basically, take into account the nativepixel size for window creation and mouse adquisition.
Due to we don't have any hardware to test directly I commit this but it can be modified in the future if any issue raises.
Thanks to @youle31 for code and review, and to @ExcaliburGO for testing
> UPBGE: Fix MacOS hidpi retina display issues

- release/scripts/startup/bl_ui/properties_data_armature.py
- release/scripts/startup/bl_ui/properties_game.py
- release/scripts/startup/bl_ui/properties_particle.py
- release/scripts/startup/bl_ui/properties_render.py
- release/scripts/startup/bl_ui/properties_texture.py
Just to remove references to 'BLENDER_GAME' which doesn't exist anymore
> UPBGE: Update release/scripts/startup

- source/blender/blenkernel/intern/object.c
- source/blender/blenkernel/intern/python_component.c
- source/blender/blenkernel/intern/sca.c
- source/blender/makesdna/DNA_controller_types.h
Used to avoid to free scripts when we shoould not.
Used also to append script at the same time than object...
Should work both in script mode and module mode.
> UPBGE: Track python controller scripts

- source/gameengine/Converter/BL_BlenderDataConversion.cpp
- source/gameengine/Physics/Bullet/CcdPhysicsEnvironment.cpp
Result of investigations comparing with 0.2.5 code.
Apparently I removed an important thing in ccdphysicsenvironment during
development. Sorry about that.
It's an attempt to fix https://github.com/UPBGE/upbge/issues/1430
I only tested with 1 file for now.
> UPBGE: Try to fix duplicates using groups

- source/gameengine/Ketsji/KX_PythonInit.cpp
It's fixing an issue in 1 of my files (background not updated with python loading another .blend in viewport render mode)
[embeddedLoadBlenderBpy.zip](https://github.com/UPBGE/upbge/files/6145671/embeddedLoadBlenderBpy.zip)
> UPBGE: Update embedded InitPythonScripting

- source/blender/blenkernel/BKE_mesh_runtime.h
- source/blender/blenkernel/intern/mesh.c
- source/blender/blenkernel/intern/mesh_runtime.c
- source/gameengine/Ketsji/KX_NavMeshObject.cpp
It is to try to fix:
https://github.com/UPBGE/upbge/issues/1437
I see no more memory leaks reported in blenderplayer
> UPBGE: Try to fix a crash with navmesh and memory leaks

- source/gameengine/Ketsji/BL_Action.cpp
The grease pencil action animation can be done animating timeoffset modifier frame parameter.
Test file: [all_modifiers.zip](https://github.com/UPBGE/upbge/files/6174614/all_modifiers.zip)
https://user-images.githubusercontent.com/1015605/111854006-741c4a00-891d-11eb-99ae-7a3886374e57.mp4
> UPBGE: Support for Grease Pencil modifiers added

- release/scripts/startup/bl_ui/properties_render.py
- source/blender/blenkernel/BKE_blender_version.h
- source/blender/blenloader/intern/versioning_defaults.c
- source/blender/blenloader/intern/versioning_upbge.c
- source/blender/draw/engines/eevee/eevee_smaa.c
- source/blender/draw/intern/draw_manager.c
- source/blender/makesdna/DNA_scene_defaults.h
- source/blender/makesdna/DNA_scene_types.h
- source/blender/makesrna/intern/rna_scene.c
- source/gameengine/Ketsji/KX_Scene.cpp
For the ones who prefer quality over performance.
> UPBGE: Add an option to render several times per frame

- source/gameengine/Ketsji/KX_Scene.cpp
attempt to fix https://github.com/UPBGE/upbge/issues/1489
Can be changed if it is causing issues
> UPBGE: Try to fix parented groupobj behaviour #1489

- release/scripts/startup/bl_ui/properties_game.py
- release/scripts/startup/bl_ui/space_logic.py
- source/blender/editors/space_buttons/buttons_context.c
- source/blender/editors/space_buttons/space_buttons.c
- source/blender/editors/space_logic/logic_ops.c
- source/blender/editors/space_logic/space_logic.c
- source/blender/makesdna/DNA_space_types.h
- source/blender/makesrna/intern/rna_space.c
- source/blender/windowmanager/WM_types.h
I did a little experiment to revamp the logic editor UI, mainly to enhance the user experience for those who prefer writing components instead of logic bricks to create an UPBGE game.
Previously, the component and properties panels resided inside the logic brick editor so it was necessary to have it open even when you don't use logic bricks at all. And because the editor takes up quite a large space, it's usually necessary to open it in a separate space, thus forcing the users constantly switching back and forth between the spaces.
As such, I moved the components and properties panel into a separate properties tab as shown below to streamline the UI:
With the change, now you can manage UPBGE components and properties from anywhere without having to open logic brick editor, while also …
> Logic editor UI enhancements

- source/blender/gpu/shaders/gpu_shader_frame_buffer_vert.glsl
- source/gameengine/Ketsji/KX_2DFilter.cpp
- source/gameengine/Rasterizer/RAS_2DFilter.cpp
- source/gameengine/Rasterizer/RAS_OpenGLFilters/RAS_VertexShader2DFilter.glsl
- source/gameengine/Rasterizer/RAS_Rasterizer.cpp
- source/gameengine/Rasterizer/RAS_Shader.cpp
I tested with several files:
[2dfilters.zip](https://github.com/UPBGE/upbge/files/6811367/2dfilters.zip)
Can be reverted with git UI if causing issues.
> UPBGE: Fixes for 2D filters on mac + 1 tmp fix on linux

- release/scripts/startup/bl_ui/properties_game.py
- source/gameengine/Converter/BL_BlenderDataConversion.cpp
- source/gameengine/Ketsji/KX_GameObject.cpp
This PR contains an assortment of minor bug fixes and enhancements related to custom game object and Python components.
> Python proxy enhancements

- source/gameengine/Converter/BL_BlenderDataConversion.cpp
- source/gameengine/Ketsji/KX_GameObject.cpp
- source/gameengine/Ketsji/KX_Scene.cpp
- source/gameengine/Ketsji/KX_Scene.h
issue at scene restart here:
https://github.com/UPBGE/upbge/issues/1531
> UPBGE: Try to fix object transform at scene restart

- source/gameengine/Ketsji/KX_Camera.cpp
- source/gameengine/Ketsji/KX_GameObject.cpp
- source/gameengine/Ketsji/KX_GameObject.h
It was fixing #765
There was an issue with property not taken into account.
I tested with this file:
[getScreenRay.zip](https://github.com/UPBGE/upbge/files/7147430/getScreenRay.zip)
and it sounds ok then I merge
> UPBGE: Recover getScreenRay work from panzergame

- source/gameengine/Ketsji/KX_GameObject.cpp
As discussed with youle on Discord.
> Suppress KX_GameObject::Update when it's suspended

- source/blender/windowmanager/xr/wm_xr.h
- source/gameengine/Ketsji/KX_Scene.cpp
@BluePrintRandom  code to make XR work in master.
> UPBGE: Fix controller update for openXR

- .github/workflows/publish-api-and-stubs.yml
Update workflow action for UPBGE 0.3 / Python 3.10.
> Update workflow action for UPBGE 0.3 / Python 3.10

- .github/workflows/publish-api-and-stubs.yml
This fixes the recently introduced CI build problem.
> Add OpenImageIO dependency to fix CI build

- source/gameengine/VideoTexture/VideoFFmpeg.cpp
- source/gameengine/VideoTexture/VideoFFmpeg.h
Fixes a build problem on Linux (e.g. AUR upbge-git package).
> Additional changes for FFmpeg 5.0 compatibility

- source/gameengine/Ketsji/KX_KetsjiEngine.cpp
- source/gameengine/Ketsji/KX_KetsjiEngine.h
This commit fixes several physics issues in the game engine
> UPBGE: Fix FrameTime manager

- source/gameengine/Physics/Bullet/CcdPhysicsEnvironment.cpp
This patch reworks the Fh spring logic in CcdPhysicsEnvironment: •	Forces are now applied along the contact normal for mesh shapes. •	Friction and anisotropic friction are only applied when the object is "considered in contact" with the ground (rough approximation: distance < margin), avoiding unwanted effects when airborne. This breaks compatibility with previous behavior, but the old logic was rarely used and produced weird results.
> UPBGE: Rework fh_spring
