source/gameengine/Ketsji/KX_SteeringActuator.cpp
source/gameengine/Ketsji/KX_SteeringActuator.h

When using a navigation mesh, exposes the steering actuator's path (list of points) to Python.
Usage: cont.actuators['Steering'].path
Uses CListWrapper as previously requested

Expose steering actuator path to Python with CListWrapper

---

doc/python_api/rst/bge_types/bge.types.KX_FontObject.rst
source/gameengine/Ketsji/KX_FontObject.cpp

I had crash with some resolutions and some sizes (Malloc returns null:
len=8690500 in glyph bitmap, total 517588916) so I changed clamp values.
test file: http://www.pasteall.org/blend/42691

UPBGE: Add resolution and size to KX_Font API and fix clamp values

---

release/scripts/startup/bl_ui/properties_game.py
source/blender/gpu/intern/gpu_framebuffer.c
source/gameengine/Ketsji/KX_KetsjiEngine.cpp
source/gameengine/Ketsji/KX_KetsjiEngine.h
source/gameengine/Ketsji/KX_WorldInfo.cpp
source/gameengine/Rasterizer/RAS_2DFilterManager.cpp
source/gameengine/Rasterizer/RAS_IRasterizer.h
source/gameengine/Rasterizer/RAS_OpenGLRasterizer/RAS_OpenGLRasterizer.cpp
source/gameengine/Rasterizer/RAS_OpenGLRasterizer/RAS_OpenGLRasterizer.h
source/gameengine/VideoTexture/ImageRender.cpp

This branch introduced fixes around the previous version of gd_fbo.
It fixes the culling quad draw for the water filter, stereo gray clear and glitch on blenderplayer resize.
@DCubix, @youle31 : Can you test this branch with the files bugged ? thanks.

Bug fixes for off screen render.

---

source/gameengine/Ketsji/KX_KetsjiEngine.cpp
source/gameengine/Ketsji/KX_KetsjiEngine.h
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/Ketsji/KX_Scene.h
source/gameengine/Launcher/LA_Launcher.cpp
source/gameengine/Physics/Bullet/CcdPhysicsEnvironment.cpp

Previously the full framerate mode incremented the clock time by the frame time step (= scale / fps) to be sure to proceed a frame with the algorithm:
```
frames = int(deltatime * m_ticrate / m_timescale + 1e-6);
```
But by doing this the clock time and the frame time was totally wrong and not constant.
To fix this issue in case of non-fixed framerate an other way was used. First the clock time is incremented only by the time from the previous frame as for fixed FPS. Second the number of frame to proceed is always set to 1. Third the frame time step is set to the increment value of the clock time.
This patch also remove the ambiguity about "fixed time" and "fixed framerate". The both therms are opposite in the code.
It was tested with physics simulation and time scaling.
@youle31, …

Fix full framerate timing issue.

---

source/gameengine/Ketsji/KX_KetsjiEngine.cpp
source/gameengine/Rasterizer/Node/RAS_DownwardNode.h
source/gameengine/Rasterizer/Node/RAS_UpwardNode.h

commented cxxabi.h
removed unused variables
Important note: To Build in debug mode, we now have to set ge_rasterizer
properties/command lines with /bigobj to build in debug mode because
of something in RAS_IBatchDisplayArray.cpp
https://drive.google.com/file/d/0B3GouQIyoCmrQXREZlFiMGtnMFU/view?usp=sharing
(picture of MSVC2015)

UPBGE: Fix compilation errors in MSVC2015 in debug mode

---

source/blender/makesrna/intern/rna_object.c

The default margin should always be 0.04. The default Cube has a margin of
0.06. This is only a bit annoying if you set this cube to rigid body,
enable collision bounds with triangle mesh, add a plane with margin of
0.04 and set the plane to static with triangle mesh because it creates a
small jitter.
This jitter doesn't occur when plane and cube have their margin set to
0.04.
But:
1) I didn't found how to change margin for default cube (it doesn't work
in versioning legacy)
2) When you add an object, its default margin is set to 0.04
3) This seems a rare bug
So I just propose to improve tooltip of margin with the following patch.
I think this is enough to answer this report:
https://github.com/UPBGE/blender/issues/484

UPBGE: Improve tooltip for margin in physics tab

---

release/scripts/startup/bl_ui/space_logic.py
release/scripts/templates_py/python_component.py
source/blender/blenkernel/BKE_python_component.h
source/blender/blenkernel/intern/python_component.c
source/blender/editors/space_logic/logic_ops.c

To ease the definition of a component a button named "Create Component" is added.
This button ask for a path module.Class and generates a script named module.py
with a component class Class inside.
This template class contains a start and update function commented
and a definition block before the class for global game engine variable.
If the file already exists an error is raised.
The previous button named Add Component is now renamed Register Component.

Add component script generation.

---

build_files/cmake/macros.cmake
build_files/cmake/platform/platform_unix.cmake
build_files/cmake/platform/platform_win32.cmake
source/gameengine/CMakeLists.txt
source/gameengine/Ketsji/KX_BoundingBox.cpp
source/gameengine/Ketsji/KX_CullingHandler.cpp
source/gameengine/Ketsji/KX_CullingHandler.h
source/gameengine/Ketsji/KX_GameObject.cpp
source/gameengine/Ketsji/KX_GameObject.h
source/gameengine/Ketsji/KX_KetsjiEngine.cpp
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/Ketsji/KX_Scene.h
source/gameengine/Ketsji/KX_TextureRendererManager.cpp
source/gameengine/VideoTexture/ImageRender.cpp

Frustum culling was improved in two ways. First, simplificate the bounding
box update. Second the test are parallelized using TBB range loop.
The bounding box update is simplified by adding the call to RAS_Deformer::UpdateBuckets
in KX_GameObject::UpdateBounds after we checked that the objects as a
bounding box. By doing this we avoid a call to GetDeformer for all objects
without a bounding box, with an unmodified bounding box or without auto
update.
All the computation of culling objects is moved into KX_CullingHandler,
this class construct it's own objects list and returns it in Process function.
Process function build a CullTask and launch it usign tbb::parallal_reduce.
Each CullTask have an operator() to test a range of object, any objects passing
the culling test is added in a task …

 UPBGE: Improve frustum culling performance.

---

source/blender/editors/space_logic/logic_window.c
source/blender/makesdna/DNA_actuator_types.h
source/blender/makesrna/intern/rna_actuator.c
source/gameengine/Converter/BL_ConvertActuators.cpp
source/gameengine/Ketsji/BL_Action.cpp
source/gameengine/Ketsji/BL_Action.h
source/gameengine/Ketsji/KX_GameObject.cpp
source/gameengine/Ketsji/KX_GameObject.h
source/gameengine/SceneGraph/SG_Node.cpp
source/gameengine/SceneGraph/SG_Node.h

Previously SG_Controller were owned and updated by SG_Node. This class
is not the best place for it as SG_Controller are not always modifying spatial,
for example Light or Camera controllers.
The best place is in BL_Action as this class was setting the simulation time
and updating the controllers indirectly.
In the same time the option "child" in action actuator which enabled recursive
time update for controllers is removed. Indeed every call to SetSimulatedTime
was followed by Update for the controllers in BL_Action.

UPBGE: Move SG_Controller entirely in BL_Action.

---

source/blender/editors/mesh/mesh_navmesh.c

Previously when the navmesh was removed from the object this one kept the OB_NAVMESH flag set and the engine tried without success to process it as a navmesh.
Now OB_NAVMESH flag is removed.
Additionally, Name for button "Navmesh Clear Data" is modified to "Remove Navmesh" to avoid possible misunderstandings.

UPBGE: Fix for bug #746 Navmesh related

---

doc/python_api/rst/bge_types/bge.types.KX_Scene.rst
source/gameengine/Ketsji/KX_KetsjiEngine.cpp
source/gameengine/Ketsji/KX_KetsjiEngine.h
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/Ketsji/KX_Scene.h

Register functions into a callback list on scenes.
```py
def example(controller):
scene = controller.owner.scene
@scene.onRemove.append
def callback(scene):
print('exiting %s...' % scene.name)
```
---
Before this there was no event to listen for the engine shutdown. I would use the `weakref` module and monitor the `bge.logic` object destruction to trigger code.
This commit adds a list of callbacks on scenes to listen for engine shutdown.

UPBGE: Add `onRemove` callbacks

---

source/blender/gpu/GPU_shader.h
source/blender/gpu/intern/gpu_shader.c
source/gameengine/Rasterizer/RAS_Shader.cpp
source/gameengine/Rasterizer/RAS_Shader.h

All the setUniform functions in BL_Shader are using name to identify the uniform,
these functions call RAS_Shader::GetUniformLocation.
This last function was naively calling indirectly glGetUniformLocation, but even
simple OpenGL calls cost more than caching.
Fortunatly OpenGL allows to enumerate all active uniforms thanks to glGetActiveUniform,
this function is used in GPUShader side inside function GPU_shader_get_uniform_infos
constructing a list of GPUUniformInfo storing the uniform location, size, type and
name.
These uniform info are used in RAS_Shader::ExtractUniformInfos which insert the
info in a map associating to the name the location, size and type> This map is then
used into GetUniformLocation.
Tested with a 4 uniforms shader and 1000 updates :
Previous : 3.26ms
Current : …

UPBGE: Avoid calling glGetUniformLocation while setting a uniform through BL_Shader.

---

doc/python_api/rst/bge_types/bge.types.KX_Mesh.rst
source/blender/python/mathutils/mathutils_bvhtree.c
source/blender/python/mathutils/mathutils_bvhtree.h
source/gameengine/Ketsji/KX_Mesh.cpp
source/gameengine/Ketsji/KX_Mesh.h

The python function KX_Mesh.constructBvh now returns a new BVH Tree
based on the mesh geometry where every indices elements of the tree
correspond to the polygons indices.
Test file:
[ge_bvhtree.zip](https://github.com/UPBGE/blender/files/2173760/ge_bvhtree.zip)

UPBGE: Implement BVH generation from KX_Mesh.

---

source/blender/blenkernel/BKE_blender.h
source/blender/blenkernel/BKE_blender_version.h
source/blender/blenkernel/intern/blender.c
source/blender/editors/space_info/info_stats.c

UPBGE: Add upbge version info to stats

---

source/blender/editors/space_view3d/view3d_draw.c
source/blender/gpu/GPU_material.h
source/blender/gpu/intern/gpu_codegen.c
source/blender/gpu/intern/gpu_draw.c
source/blender/gpu/intern/gpu_material.c
source/blender/gpu/shaders/gpu_shader_material.glsl
source/gameengine/Converter/BL_BlenderDataConversion.cpp
source/gameengine/Ketsji/BL_BlenderShader.cpp
source/gameengine/Ketsji/BL_BlenderShader.h
source/gameengine/Ketsji/KX_BlenderMaterial.cpp
source/gameengine/Ketsji/KX_BlenderMaterial.h
source/gameengine/Ketsji/KX_FontObject.cpp
source/gameengine/Ketsji/KX_GameObject.cpp
source/gameengine/Ketsji/KX_TextMaterial.cpp
source/gameengine/Ketsji/KX_TextMaterial.h
source/gameengine/Ketsji/KX_WorldInfo.cpp
source/gameengine/Rasterizer/RAS_BucketManager.cpp
source/gameengine/Rasterizer/RAS_BucketManager.h
source/gameengine/Rasterizer/RAS_IPolygonMaterial.h
source/gameengine/Rasterizer/RAS_MeshUser.cpp
source/gameengine/Rasterizer/RAS_MeshUser.h
source/gameengine/Rasterizer/RAS_TextureRenderer.cpp

Previously the ligthing of the objects based on a layer was fixed
at the conversion time by the construction of BL_BlenderShader
with the member m_lightLayer. Also because of the blender
material managment the object layer was used only when binding
the material and not when binding object dependent uniforms.
The situation is changed firstly because the usage of one
layer for all the object using the same material is totally wrong.
Secondly the layers were not dynamic per object.
To solve this situation the fastest way is to expose a layer into
the shader, the function lamp_visible is designed for. It receives
the lamp layer, object layer, lamp color and lamp energy and
updates out color and energy if the lamp layer mask the object
layer, to avoid branching the test computes a value of 0 …

UPBGE: Implement dynamic object ligthing layer.

---

source/gameengine/Converter/BL_BlenderDataConversion.cpp
source/gameengine/Converter/BL_BlenderDataConversion.h
source/gameengine/Converter/BL_Converter.cpp
source/gameengine/Converter/BL_Converter.h
source/gameengine/Converter/BL_SceneConverter.cpp
source/gameengine/Converter/BL_SceneConverter.h
source/gameengine/Ketsji/KX_BlenderMaterial.cpp
source/gameengine/Ketsji/KX_BlenderMaterial.h
source/gameengine/Ketsji/KX_KetsjiEngine.cpp
source/gameengine/Ketsji/KX_LibLoadStatus.cpp
source/gameengine/Ketsji/KX_LibLoadStatus.h
source/gameengine/Ketsji/KX_PythonComponentManager.cpp
source/gameengine/Ketsji/KX_PythonComponentManager.h
source/gameengine/Ketsji/KX_PythonInit.cpp
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/Rasterizer/Node/RAS_RenderNode.h
source/gameengine/Rasterizer/RAS_AttributeArray.h
source/gameengine/Rasterizer/RAS_BoundingBox.cpp
source/gameengine/Rasterizer/RAS_DebugDraw.cpp
source/gameengine/Rasterizer/RAS_DebugDraw.h
source/gameengine/Rasterizer/RAS_Rasterizer.cpp
source/gameengine/Rasterizer/RAS_Rasterizer.h

Previously the async thread dedicated for the libload was directly calling
python function without ensuring the GIL and this caused issue, no conversion
or memory error.
To fix this issue Py_X_ALLOW_THREADS and Py_X_THREADS macro are used, they
intent on ensuring and locking the python GIL so that any python API calls
are proceeded sequentially.
Fix issue #751.

UPBGE: Fix python component conversion from async libload.

---

source/blender/gpu/intern/gpu_shader.c

This patch with the condition of ARB_compatiblity allow to select an higher GLSL version.
ARB_compatibility is needed as > GLSL 150 doesn't support builtin natives.

Enable more GLSL versions.

---

source/gameengine/Ketsji/KX_Camera.cpp
source/gameengine/Ketsji/KX_GameObject.cpp
source/gameengine/Ketsji/KX_GameObject.h

Previously the function getScreenRay was adapted to only perspective
cameras because the ray cast was always starting from the center of
the camera.
In case of orthographic the ray cast should start from a point unprojected
from the near plane and continue to in the direction of the camera
(-Z orientation axis).
This is proceeded in getScreenRay and the indirect call to getScreenVect
is removed.

UPBGE: Fix orthographic camera getScreenRay.

---

release/scripts/startup/bl_ui/space_logic.py
source/blender/makesdna/DNA_python_component_types.h
source/blender/makesrna/intern/rna_python_component.c

Previously the components name was exposed by a property non-editable which
was rendered in light gray and the component box was always expanded.
Also the module name was inaccesible from bpy.
The last issue is simply solved by exposing the "module" string to RNA.
The name property is replaced by a label in the UI. To expanse the box
the property "show_expanded" similar to the logic brick is implemented,
when this property is True, an inner box is generated containing all the
properties.
Fix issue #793.

UPBGE: Improve component UI.

---

source/gameengine/Converter/BL_BlenderDataConversion.cpp
source/gameengine/Ketsji/KX_GameObject.cpp

Previously objects were considered as occluder if the occluder option
was checked and that the object was visible. The last constraint is
bothering for the user that could define a simplified mesh for occlusion
that naturally will not be visible.
This commit is introducing the condition "visible || occluder" for the
call activating the graphic controller in KX_GameObject::SetVisible/
SetOccluder and the initialization of the graphic controller.
Fix issue #807.

UPBGE: Enable occluder for invisible objects.

---

release/scripts/startup/bl_ui/properties_game.py
release/scripts/startup/bl_ui/properties_scene.py
release/scripts/startup/bl_ui/space_view3d.py
source/blender/render/intern/source/external_engine.c

Some unused options/entities are removed from the UI in game engine mode:
- scene keying set
- scene audio
- speaker and forec filed in add menu
Also the game engine is renamed UPBGE.
Fix issue #756.

UPBGE: Cleanup UI.

---

doc/python_api/rst/bge_types/bge.types.KX_Mesh.rst
source/gameengine/Ketsji/KX_Mesh.cpp

The function KX_Mesh.constructBvh can now use as first argument
a transform 4x4 matrix used over all the vertices. This allow
the user to create a BVH in world space by passing the object
world transform.
Fix issue #786.

UPBGE: Allow constructing mesh BVH with a transform.

---

CMakeLists.txt
source/blender/windowmanager/intern/wm_files.c

When the user pref config isn't saved, blender load one from memory and
call the function BLO_update_defaults_userpref_blend to initialize properly
the preferences such as the auto exec script option defaulted to true.
Unfortunatly this function is called after the check of the option
and so for blender auto exec is always false until the user saves the
preferences and reload.

UPBGE: Fix default auto exec option for new created user prefs.

---

doc/python_api/rst/bge.logic.rst
doc/python_api/rst/bge_types/bge.types.KX_LibLoadStatus.rst
source/gameengine/Ketsji/KX_PythonInit.cpp

async is a reserved word in Pyhon 3.7
Check: https://docs.python.org/3.7/whatsnew/3.7.html#summary-release-highlights
This Fix #826 .
The python rst modification should be commited here and UPBGE-Docs repository or only here or only there?

UPBGE: Rename async parameter from LibLoad as is a reserved word

---

source/blender/gpu/GPU_shader.h
source/blender/gpu/intern/gpu_shader.c
source/gameengine/Rasterizer/RAS_Shader.cpp
source/gameengine/Rasterizer/RAS_Shader.h

Since uniform caching the user was unable to precise the name of
an uniform array item such as colors[42].
This is caused by an ambiguity in the OpenGL function glGetActiveUniform
regarding arrays. If the arrays is of struct type then all the items are
returned by glGetActiveUniform. Else for simple array in main program
of in struct but of primitive type, then only the first element is
returned e.g colors[0].
Two choices were proposed:
- Detecting the array name format and discard caching mechanism while
asking for a location.
- Simulating all item names and store all theirs locations.
The second option is selected in this commit for multiple advantages
over the first:
- Detecting the format of an array name could be complicated as the
program have to manage the case the user is …

UPBGE: Fix uniform caching of arrays.

---

source/gameengine/Ketsji/KX_KetsjiEngine.cpp

Previously the time step (base of frame step) was set to the
fixed frame step (1 / FPS * scale) when the user was using external
clock (setting the clock manually).
This commit introduces a different behaviour: the timestep is the
elapsed time bewteen two clock set of the user.

UPBGE: Set frame step to elapsed time in case of external clock.

---

source/gameengine/Converter/BL_BlenderDataConversion.cpp
source/gameengine/Ketsji/KX_NavMeshObject.cpp
source/gameengine/Ketsji/KX_NavMeshObject.h

Previously the navmesh rebuilding was failing because of two issues,
first the mesh used as source was always the one from the blender object
secondly the navmesh itself wasn't updated in the obstacle simulation.
To solve this first issue the function BuildVertIndArrays is calling
two sub functions, BuildFromDerivedMesh for creating from a derived
mesh and benefit from CD_RECAST layer, if this function fails to get
the recast layer BuildFromMesh is called and generate information from
a RAS_Mesh without detailed meshes.
In this last function the indices computation is solved by the requirement
of Detour library to use 6 indices per polygon, the unused indices are
discarded by value 0xFFFF.
The second issue is solved by calling AddObstaclesForNavMesh only from …

UPBGE: Fix navmesh rebuild after mesh replacement.

---

source/blender/makesdna/DNA_scene_types.h
source/gameengine/BlenderRoutines/KX_BlenderCanvas.cpp
source/gameengine/BlenderRoutines/KX_BlenderCanvas.h
source/gameengine/GamePlayer/GPG_Canvas.cpp
source/gameengine/GamePlayer/GPG_Canvas.h
source/gameengine/Ketsji/KX_PythonInit.cpp
source/gameengine/Launcher/LA_Launcher.cpp
source/gameengine/Launcher/LA_Launcher.h
source/gameengine/Rasterizer/RAS_ICanvas.cpp
source/gameengine/Rasterizer/RAS_ICanvas.h

Previously bge.render.getVsync wasn't returning the value set by setVsync when
VSYNC_ADAPTIVE was used. It can be justified by the fact that adaptive is set
by using a negative swap interval value but the GLX get function still returns
a positive swap interval value and the flag GLX_LATE_SWAPS_TEAR_EXT meaning
adaptive is enabled.
In any case GLX could refuse a swap interval and the user should be able to do
setVsync(getVsync()) with no change on the swap control. To achieve this behaviour
RAS_ICanvas store the current swap control in a enum variable m_controlSwap,
this variable is used in getter GetSwapControl used by bge.render.getVsync().
The setter is virtual and overloaded in each canvas implementation, they use
a common table to find the swap interval associated to the swap control …

UPBGE: Fix bge.render.[get/set]Vsync.

---

source/blender/gpu/GPU_material.h
source/blender/gpu/GPU_shader.h
source/blender/gpu/intern/gpu_codegen.c
source/blender/gpu/intern/gpu_material.c
source/blender/gpu/intern/gpu_shader.c
source/blender/gpu/shaders/gpu_shader_vertex.glsl
source/gameengine/Ketsji/BL_BlenderShader.cpp
source/gameengine/Ketsji/BL_BlenderShader.h
source/gameengine/Ketsji/KX_BlenderMaterial.cpp
source/gameengine/Ketsji/KX_BlenderMaterial.h
source/gameengine/Ketsji/KX_TextMaterial.cpp
source/gameengine/Ketsji/KX_TextMaterial.h
source/gameengine/Rasterizer/Node/RAS_RenderNode.h
source/gameengine/Rasterizer/RAS_DisplayArrayBucket.cpp
source/gameengine/Rasterizer/RAS_DisplayArrayBucket.h
source/gameengine/Rasterizer/RAS_IMaterial.h
source/gameengine/Rasterizer/RAS_InstancingBuffer.cpp
source/gameengine/Rasterizer/RAS_InstancingBuffer.h
source/gameengine/Rasterizer/RAS_Rasterizer.cpp
source/gameengine/Rasterizer/RAS_Rasterizer.h

In recent commit material object layer was introduced as an uniform used
to compute light visibility. But the geometry instancing wasn't defaulting
this layer (bad option) or setting it with an instance attribute (best option).
In consideration RAS_InstancingBuffer must prepare a buffer with layer data
packed in.
The instancing attributes could be just extended but this will introduce
performance decrease for all other cases not using layer (shadow/wire) same
as the object color attribute is doing currently.
To avoid this drawback, RAS_InstancingBuffer is configured for a combination
of attributes and uniquelly stored per drawing mode.
The attributes deserve object color (COLOR_ATTRIB) or object layer
(LAYER_ATTRIB). Position and matrix attributes are defaulted (DEFAULT_ATTRIBUTE).
The …

UPBGE: Fix geometry instancing ligthing.

---

source/gameengine/Common/CM_Clock.cpp
source/gameengine/Common/CM_Clock.h
source/gameengine/Ketsji/KX_KetsjiEngine.cpp
source/gameengine/Ketsji/KX_KetsjiEngine.h

Previously a commit introduce for external clock the targeting of one frame
at every call to NextFrame, not more.
The original behaviour is if the user enabled fixed framerate then compute
as many as frame possible respecting the FPS value (m_ticrate).
This behaviour is restored in the refactor.
The refactor is simplyfing the time calculation and isolating it.
The function KX_KetsjiEngine::GetFrameTimes is returning a struct FrameTimes
with the number of frames to proceed and the time/frame step.
Inside this function we first update the clock time if the user isn't (case
of external clock) then the elapsed time is computed. Next the timestep and
frame number are computed using fixed value or elapsed time. The number of frame
is clamped by max logic/physics frame using the simple method: …

UPBGE: Fix and simplify frame time management.

---

source/gameengine/Common/CM_Map.h
source/gameengine/Converter/BL_BlenderDataConversion.cpp
source/gameengine/Converter/BL_SceneConverter.cpp
source/gameengine/Converter/BL_SceneConverter.h
source/gameengine/Ketsji/KX_BlenderMaterial.cpp
source/gameengine/Ketsji/KX_BlenderMaterial.h

The issue #855 reports a bug related to the cube and planar map, this is explained
by the fact that the texture renderers try to convert before the textures are
available.
The texture are converted in reload material step which is proceeded after conversion
and post conversion. In the same time leaving texture renderer conversion the ability
to be mutlithread could be very dangerous as they could create FBO and manipulate
any other OpenGL setting for initialization.
The issue is solved by making KX_BlenderMaterial::InitTextures public and call it
into post conversion step and move after in the same step the conversion of
texture renderers.
As the scene converter is constant in post conversion (it's forbidden to create
data but allowed to modify) the function starting with Find are now …

UPBGE: Fix conversion of realtime maps.

---

extern/bullet/src/BulletDynamics/Character/btKinematicCharacterController.cpp
extern/bullet/src/BulletDynamics/Character/btKinematicCharacterController.h
extern/bullet/src/BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp
source/gameengine/Physics/Bullet/CcdPhysicsController.cpp
source/gameengine/Physics/Bullet/CcdPhysicsController.h

Chracter controller is using a ghost object and in particular
a ghost object caching collision pairs named btPairCachingGhostObject.
But with the recent update of bullet, we realized after some bug
reported around character that the caching of collision is not
anymore supported in a safe way.
Instead of fixing the caching mechanism, it was choose to replace
btPairCachingGhostObject by btGhostObject.
The btGhostObject is already maintaining a cache of object overlapping
the only step added is asking the pair cache in the world dispatcher
for the character ghost and one of its overlapping objects.
By this way the character is just reading and not managing duplication
or deletion of manifold in its own cache which is the safest solution.
In the same time the function …

UPBGE: Fix character collision detection.

---

doc/python_api/rst/bge_types/bge.types.BL_Texture.rst
doc/python_api/rst/bge_types/bge.types.KX_2DFilterManager.rst
doc/python_api/rst/bge_types/bge.types.KX_2DFilterOffScreen.rst
doc/python_api/rst/bge_types/bge.types.KX_BatchGroup.rst
doc/python_api/rst/bge_types/bge.types.KX_BoundingBox.rst
doc/python_api/rst/bge_types/bge.types.KX_LodLevel.rst
doc/python_api/rst/bge_types/bge.types.KX_LodManager.rst
doc/python_api/rst/bge_types/bge.types.KX_PythonComponent.rst
doc/python_api/rst/bge_types/bge.types.KX_TextureRenderer.rst
doc/python_api/rst/bge_types/bge.types.KX_WorldInfo.rst
doc/python_api/rst/bge_types/bge.types.SCA_InputEvent.rst
doc/python_api/rst/bge_types/bge.types.SCA_PythonMouse.rst

The issue #865 reported a recurrent user issue concerning the normalization
of mouse coordinates. The user must be aware to use floor division and normalized
by dividing by width or height minus 1.
Fix issue: #865.

UPBGE: Add documentation example for mouse center normalization.

---

doc/python_api/rst/bge_types/bge.types.KX_BatchGroup.rst
source/gameengine/Ketsji/BL_BlenderShader.cpp
source/gameengine/Ketsji/BL_BlenderShader.h
source/gameengine/Ketsji/BL_Shader.cpp
source/gameengine/Ketsji/BL_Shader.h
source/gameengine/Ketsji/KX_BatchGroup.cpp
source/gameengine/Ketsji/KX_BatchGroup.h
source/gameengine/Ketsji/KX_BlenderMaterial.cpp
source/gameengine/Ketsji/KX_BlenderMaterial.h
source/gameengine/Ketsji/KX_TextMaterial.cpp
source/gameengine/Ketsji/KX_TextMaterial.h
source/gameengine/Rasterizer/RAS_BatchGroup.cpp
source/gameengine/Rasterizer/RAS_BatchGroup.h
source/gameengine/Rasterizer/RAS_DisplayArrayBucket.cpp
source/gameengine/Rasterizer/RAS_IMaterial.h
source/gameengine/Rasterizer/RAS_MeshSlot.cpp

Previously object render settings such as light layer or object color
were not managed for batching groups.
For attribute like layers we can choose to make an union of all objects
layers, but in case of color there's no meaning of union.
To solve this issue one object should be used as reference for the group.
The attribute KX_BatchGroup.referenceObject is defined and initialized
to the first merged object when creating a batch group.
Later the user can change it to an other object of the same group.
Internally this object is set in KX_BatchGroup and RAS_BatchGroup,
KX_BatchGroup see a KX_GameObject and RAS_BatchGroup only the RAS_MeshUser
of this object. This mesh user is retrieved in RAS_DisplayArrayBucket::RunBatchingNode
from the first mesh slot mesh user and passed to …

UPBGE: Fix object render settings for batching groups.

---

release/scripts/startup/bl_ui/properties_data_empty.py
release/scripts/startup/bl_ui/properties_texture.py
release/scripts/startup/bl_ui/space_image.py
source/blender/blenkernel/intern/texture.c
source/blender/blenloader/intern/versioning_upbge.c
source/blender/editors/include/UI_interface.h
source/blender/editors/space_image/CMakeLists.txt
source/blender/editors/space_image/image_buttons.c
source/blender/editors/space_node/drawnode.c
source/blender/gpu/intern/gpu_material.c
source/blender/makesdna/DNA_texture_types.h
source/blender/makesrna/intern/rna_material.c
source/blender/makesrna/intern/rna_scene.c
source/blender/makesrna/intern/rna_ui_api.c
source/blenderplayer/bad_level_call_stubs/stubs.c

With the introduction of color management, every scene render is
in linear color space and the final draw to the screen (potentially
after filters) might be in sRGB space.
This behvaiour has the side effect of leaving ImageRender/ImageViewport
images in linear spaces as they result from a scene render. But all
blender textures were before supposed to be sRGB space and converted
back into linear in material shaders. Now it is partially the case.
The way of fixing this issue is to leave an option in material texture
panel to select color space of the image. The default is sRGB and
texture sapped with ImageRender in game must select Linear space.
Realtime envmap always ignore this setting as they are in linear
space in any cases.

UPBGE: Fix color space of ImageRender textures.

---

source/gameengine/Expressions/EXP_PythonCallBack.h
source/gameengine/Expressions/intern/PythonCallBack.cpp
source/gameengine/Ketsji/KX_LibLoadStatus.cpp

Previously KX_LibLoadStatus finish callback was only permitted to be
python function not method.
To allow calling a method, work from EXP_RunPythonCallBackList is reused
and the calling of a python function is moved into new function
EXP_RunPythonCallback. This function is in charge of checking that the
python object is callable and construct a tuple of the arguments.
EXP_RunPythonCallback is now called into KX_LibLoadStatus::RunFinishCallback.

UPBGE: Allow KX_LibLoadStatus.onFinish to call python method.

---

source/gameengine/BlenderRoutines/KX_BlenderCanvas.cpp
source/gameengine/BlenderRoutines/KX_BlenderCanvas.h
source/gameengine/GamePlayer/GPG_Canvas.cpp
source/gameengine/GamePlayer/GPG_Canvas.h
source/gameengine/Launcher/LA_BlenderLauncher.cpp
source/gameengine/Launcher/LA_BlenderLauncher.h
source/gameengine/Launcher/LA_Launcher.cpp
source/gameengine/Launcher/LA_Launcher.h
source/gameengine/Launcher/LA_PlayerLauncher.cpp
source/gameengine/Launcher/LA_PlayerLauncher.h
source/gameengine/Rasterizer/RAS_ICanvas.cpp
source/gameengine/Rasterizer/RAS_ICanvas.h

Since 23183936242af, in KX_BlenderCanvas constructor, UpdateOffScreens
was called and and a new offscreen was created, but the number of AA
samples was set to 0, the the offscreen was not created correctly.
To fix that, we can set the samples number in canvas constructor. This
way, the number of AA samples is available when we create the offscreen

UPBGE: Fix Antialiasing setting at game engine start

---

release/scripts/startup/bl_ui/properties_game.py
source/blender/blenkernel/intern/lamp.c
source/blender/blenloader/intern/versioning_upbge.c
source/blender/gpu/GPU_framebuffer.h
source/blender/gpu/intern/gpu_framebuffer.c
source/blender/gpu/intern/gpu_material.c
source/blender/makesdna/DNA_lamp_types.h
source/blender/makesrna/intern/rna_lamp.c
source/blender/render/intern/include/render_types.h
source/blender/render/intern/source/convertblender.c
source/gameengine/Converter/BL_BlenderDataConversion.cpp
source/gameengine/Rasterizer/RAS_ILightObject.h

The default value is 1 (as current default) but the recommended value for quality/real shadows is 2 or 3.
Max 4 passes. To use with care because it is expensive.

UPBGE: Expose the number of blur passes for variance shadow maps

---

source/gameengine/Ketsji/KX_TextureRendererManager.cpp

In cubemap/planar rendering process, this:
void RAS_TextureRenderer::EndRender(RAS_Rasterizer *rasty, unsigned
short layer)
{
m_layers[layer].Unbind(m_useMipmap);
}
was not called. To generate mipmap, we have to call it each frame.
This is an attempt to fix https://github.com/UPBGE/blender/issues/998
This would need to be reviewed by panzergame or lordloki

UPBGE: Try to fix mipmap for cubemap textures

---

source/gameengine/Ketsji/KX_GameObject.cpp

Remove parent was not updating the child shape of compound child
objects,it was checking to see if the root was compound, after it
already removed it's parent.

UPBGE: fix compound child remove parent

---

release/scripts/startup/bl_ui/properties_render.py
source/blender/draw/DRW_engine.h
source/blender/draw/intern/DRW_render.h
source/blender/editors/space_view3d/view3d_draw.c
source/blender/makesdna/DNA_scene_types.h
source/blender/makesrna/intern/rna_scene.c
source/gameengine/BlenderRoutines/KX_BlenderCanvas.cpp
source/gameengine/BlenderRoutines/KX_BlenderCanvas.h
source/gameengine/Converter/BL_BlenderDataConversion.cpp
source/gameengine/GamePlayer/GPG_Canvas.cpp
source/gameengine/GamePlayer/GPG_Canvas.h
source/gameengine/Ketsji/CMakeLists.txt
source/gameengine/Ketsji/KX_BlenderMaterial.cpp
source/gameengine/Ketsji/KX_KetsjiEngine.cpp
source/gameengine/Ketsji/KX_KetsjiEngine.h
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/Launcher/LA_Launcher.cpp
source/gameengine/Rasterizer/RAS_ICanvas.h

This is not perfect, but I think it can be merged. This is really fun.
Maybe we should avoid the beginning of the render loop in KX_KetsjiEngine and move the code here
to render only the main scene and the main camera.
But as an experimental option it's cool

UPBGE: Add an option to use viewport render directly in embedded

---

release/scripts/startup/bl_ui/properties_object.py
source/blender/draw/engines/eevee/eevee_engine.c
source/blender/draw/engines/eevee/eevee_materials.c
source/blender/draw/engines/eevee/eevee_private.h
source/blender/editors/space_logic/logic_window.c
source/blender/makesdna/DNA_actuator_types.h
source/blender/makesdna/DNA_object_types.h
source/blender/makesrna/intern/rna_actuator.c
source/blender/makesrna/intern/rna_object.c
source/gameengine/Converter/KX_ConvertActuators.cpp
source/gameengine/GameLogic/SCA_DynamicActuator.cpp
source/gameengine/GameLogic/SCA_DynamicActuator.h

There are 2 parts:
1. Show in front option is implemented for eevee render to have the possibility to display HUD objects in front of other scene objects.
2. Dynamic actuator logic is completed. It's not only available for mesh objects OB_MESH but for all types of objects AND we can DISABLE/ENABLE PHYSICS for all children of an object.
It takes example on Visible actuator.
Using Visibility actuator + Dynamic actuator, we can hide/suspend physics for all objects of the HUD OR unhide/restore physics for all objects of the HUD (physics can be needed if we want to have the HUD objects clickable).
The HUD design should look like this:
Show in front option for HUD objects is here:
The root Empty of the HUD (main parent for all HUD objects) can be parented to main Camera to follow main Camera …

UPBGE: Add a system to do HUDs without overlay scenes

---

source/gameengine/Ketsji/KX_GameObject.cpp

clang 8.0 reports error passing non-trivial type to variadic function
fix by using .c_str()
```
upbge-8fecba4e7005/source/gameengine/Ketsji/KX_GameObject.cpp:2567:3: error: cannot pass object of non-trivial type 'const std::string' (aka 'const basic_string<char, char_traits<char>, allocator<char> >') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
PYTHON_CHECK_PHYSICS_CONTROLLER(self, attrdef->m_name, nullptr);
^
upbge-8fecba4e7005/source/gameengine/Ketsji/KX_GameObject.cpp:1646:86: note: expanded from macro 'PYTHON_CHECK_PHYSICS_CONTROLLER'
PyExc_AttributeError, "KX_GameObject.%s, is missing a physics controller", (attr)); \
^
1 error generated.
```

Fix error passing non-trivial type to variadic function

---

source/blender/draw/intern/DRW_render.h
source/blender/draw/intern/draw_manager.c
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/Ketsji/KX_Scene.h
source/gameengine/VideoTexture/ImageRender.cpp
source/gameengine/VideoTexture/ImageRender.h

Simplified because I don't think we can use Render to Offscreen with this implementation.
But we can render something to a texture and use the rendered texture bindId to do things with in a 2D filter if we want.
Else, contrarly to old bge, the rendered textures are shaded, which is great.
I hope i didn't do too much mistakes, but i did few tests and it seemed ok.
The test files links are in some of the commits I did

UPBGE: Restore a simplified version of ImageRender

---

source/gameengine/Ketsji/KX_2DFilter.cpp
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/Ketsji/KX_Scene.h
source/gameengine/Launcher/LA_Launcher.cpp
source/gameengine/Rasterizer/RAS_2DFilterFrameBuffer.cpp
source/gameengine/Rasterizer/RAS_FrameBuffer.cpp
source/gameengine/Rasterizer/RAS_FrameBuffer.h
source/gameengine/Rasterizer/RAS_Rasterizer.cpp
source/gameengine/Rasterizer/RAS_Rasterizer.h

Test file for 2dfilter offscreens:
http://pasteall.org/blend/index.php?id=52710
Notes:
1. As in 2.8 branch we use framebuffers instead of offscreens, i renamed
files and many variables, functions.... frameBuffer instead of
offScreen.
KX_2DFilterOffScreen is now KX_2DFilterFrmaeBuffer
same for RAS_2DFilterOffScreen > RAS_2DFilterFrameBuffer
but on scripting side, I see no issue to keep "offScreen" name for backward
compatibility.
Anyway, i doubt there are many people who use this.
2. KX_2DFilterOffScreen supported several color attachments per
offscreen, but I restored only 1 color attachment because it's simpler

UPBGE: Small reorganisation of Render code an restore 2DFilterOffScreens

---

source/blender/draw/engines/eevee/eevee_engine.c
source/blender/draw/engines/eevee/eevee_lightprobes.c
source/blender/draw/engines/eevee/eevee_materials.c
source/blender/draw/intern/DRW_render.h
source/blender/draw/intern/draw_manager.c
source/blender/gpu/GPU_viewport.h
source/blender/gpu/intern/gpu_viewport.c
source/blender/makesdna/DNA_scene_types.h
source/gameengine/Converter/BL_BlenderDataConversion.cpp
source/gameengine/Converter/KX_BlenderConverter.h
source/gameengine/Ketsji/KX_Camera.cpp
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/Ketsji/KX_Scene.h
source/gameengine/Rasterizer/RAS_2DFilterFrameBuffer.cpp
source/gameengine/Rasterizer/RAS_FrameBuffer.cpp
source/gameengine/Rasterizer/RAS_OpenGLRasterizer/RAS_OpenGLLight.cpp
source/gameengine/Rasterizer/RAS_Rasterizer.cpp
source/gameengine/VideoTexture/ImageRender.cpp
source/gameengine/VideoTexture/ImageRender.h
source/gameengine/VideoTexture/Texture.cpp

I added gpencil engine to test.
Before, only eevee engine was enabled in game engine render loop.
The render loop returned the final_tex rendered by eevee and was displayed in bge.
But I had another look at render code and they do differently.
A GPUViewport is bound before drawing.
All engines are rendered and at the end of each engine render loop, the returned color is written into the GPUViewport framebuffer (which can be accessed for example with DRW_viewport_framebuffer_list_get()->default_fb)
Then the GPUViewport is unbound.
Then finally we can access the viewport texture which has accumulated the results of all enabled engines with GPU_viewport_color_texture(viewport).
Then I refactored the game engine render loop in this way to have the possibility to use several engines. …

UPBGE: Support several engines drawing

---

source/blender/blenkernel/BKE_mesh_runtime.h
source/blender/blenkernel/intern/mesh.c
source/blender/blenkernel/intern/mesh_runtime.c
source/gameengine/Launcher/LA_BlenderLauncher.cpp

Now, we don't free navmesh id as it is not based in id.
Additionally, we improve undo system including undo based in step name.

UPBGE: Fix for #1104, engine crash on exit due to NavMesh free data

---

source/gameengine/Ketsji/KX_ConstraintWrapper.cpp
source/gameengine/Ketsji/KX_ConstraintWrapper.h
source/gameengine/Ketsji/KX_PyConstraintBinding.cpp

This is inspired by old bge code which had not this issue. I think this comes from the way constraints are created with NewProxy(true)

UPBGE: Try to fix crash when removing bge.constraint in some cases

---

source/gameengine/Converter/BL_ArmatureObject.cpp

Following compiler error messages.
I use blender code instead of game_copy_pose
and I use BKE_pose_copy_data with constraints = true because
BKE_pose_free tries to free constraints

UPBGE: Try to fix a crash with m_blendpose free

---

release/darwin/Blenderplayer.app/Contents/Info.plist
release/scripts/startup/bl_operators/wm.py
source/blenderplayer/CMakeLists.txt
source/creator/CMakeLists.txt

Apple treats both executables in a self-contained manner. Therefore we have to copy all the resources for the blenderplayer as well.

UPBGE: Rework blenderplayer CMakeLists.txt for MacOS

---

release/scripts/presets/keyconfig/keymap_data/blender_default.py
source/blender/editors/space_logic/space_logic.c

During 2.8 development, as keymap system changed a bit and as I don't use it, I commented the code.
Here I tried to adapt the code for 2.8 as I saw someone asked this on BA

UPBGE: Restore logic editor keymap (shortcuts)

---

source/blender/draw/engines/basic/basic_engine.c
source/blender/draw/intern/draw_manager.c

previously we had crashes related to basic engine depth conservative shader.
The reason is that when we finalized the game engine the basic engine was freed (freeing the depth_conservative shader) but the depth shader wasn't freed as it is a built-in shader and it uses another procedure.
Then when we are initializing again the basic engine for Blender we only were checking for depth shader inexistence to create both shaders but we could have the case that depth shader exists but depth_conservative shader not.
To avoid that we separate the creation of both shaders checking for its existence indepently.

UPBGE: Recover use of DRW_engines_free

---

source/blender/draw/engines/eevee/eevee_volumes.c

When the TAA was used, the current code avoided to use the history buffer for the temporal volumetric integration. It used a some kind of simplification.
Instead of it, we use the history buffer to "mix" the volumetric from one frame to another (as it was recommended by https://es.slideshare.net/DICEStudio/physically-based-and-unified-volumetric-rendering-in-frostbite and only used for viewport offline rendering until now). 
Regarding performance i didn't see negative effects.

UPBGE: Fix volumetric banding

---

release/scripts/startup/bl_ui/properties_render.py
source/blender/draw/engines/eevee/eevee_volumes.c
source/blender/makesdna/DNA_scene_types.h
source/blender/makesrna/intern/rna_scene.c

volumes patch)
This is a patch to answer IzaZed request here:
https://github.com/UPBGE/upbge/issues/1188
Notes:
When we are working in the viewport, the volumes are updated quicker
when volumes blending is not enabled then it's ok for me to have the
choice to toggle between both behaviours
A test file: https://pasteall.org/blend/c5629cf90d1a402897ab6fca3f7fc384

UPBGE: Add a button to enable/disable volumetric blending (lordloki

---

release/scripts/startup/bl_ui/space_logic.py
source/blender/blenkernel/intern/python_component.c
source/blender/editors/space_logic/logic_ops.c
source/blender/makesdna/DNA_python_component_types.h
source/blender/makesrna/intern/rna_python_component.c

This is fixing https://github.com/UPBGE/upbge/issues/1230
I copied, the old DNA_python_component.h, rna_python_component, python_component.c, the space_logic.py ui, the part of logic_ops related to python components.
I didn't touched to the code in gameengine folder.
I need to test. Idk if you prefer recover commits by commits or do the stuff like that.
I create a pull request to have a better view

UPBGE: Recover last version of python components

---

source/gameengine/Ketsji/KX_GameObject.cpp

Random fix
Idk why cam matrix doesn't like RestoreObmat code.
Calling RestoreObmat cause issues when we restart a scene with a camera
parented to an object like in this file:
https://pasteall.org/blend/6bab5870d9ef4c9d91ea9a6f80321c0e

UPBGE: Try to fix camera matrix when restart game

---

source/gameengine/Ketsji/KX_Camera.cpp
source/gameengine/Ketsji/KX_TextureRendererManager.cpp
source/gameengine/Ketsji/KX_TextureRendererManager.h

cam projmat settings change
KX_TextureRenderers projection matrix must be invalidated if sceneCamera
used change of projection matrix (if camera lens changes for example)
It is a fix proposal for this bug report:
https://github.com/UPBGE/upbge/issues/1255

UPBGE: Fix wrong projection matrix used by texture renderers when main

---

source/gameengine/Ketsji/BL_Action.cpp
source/gameengine/Ketsji/CMakeLists.txt
source/gameengine/Ketsji/KX_GameObject.cpp
source/gameengine/Ketsji/KX_GameObject.h
source/gameengine/Ketsji/KX_PythonInit.cpp

Fluid: https://pasteall.org/blend/bca2c52db77b49068ac069c694dd38ba
Smoke: https://pasteall.org/blend/b5579b5a9649426b9427f9d297503b24
When we call ID_RECAL_TRANSFORM on orig_objects with a fluid modifier or a
smoke modifier, it enables heavy computations in
BKE_fluid_modifier_do...
When we only change ob_eval obmat, it's ok. Except that smoke doesn't seem to
move, but at least there's no freeze.
There are still some issues with blenderplayer but part of issues can be solved if we indicate the absolute path of the fluid cache.
Else, there's a warning displayed in blenderplayer which says that bpy_import_main_set has not been called. It can be a threading issue but I'm not sure for now. There are maybe some things that we can pick from bpy_interface to try to understand.
But in a first …

 UPBGE: Try to fix freeze when we run files with fluids

---

source/blender/draw/intern/draw_manager.c
source/gameengine/Ketsji/KX_KetsjiEngine.cpp
source/gameengine/Rasterizer/RAS_OpenGLRasterizer/RAS_OpenGLDebugDraw.cpp

With recent eevee's refactor, there were issues with post draw.
I tried to have the render in this depth order:
1) scene 2) physics debug 3) post_draw 4) profile drawing
It needs to switch between matrix and depth tests but seems to work with this file:
https://pasteall.org/blend/4671296344af4604ad36af9845ead5a1
Note: I removed the pre/post draw callbacks from blender because they are now using an overlay-fb which is not in use in bge draw loop.
Picture:

UPBGE: Try to restore post_draw callbacks

---

source/blender/draw/intern/draw_manager.c
source/blender/editors/space_view3d/view3d_view.c
source/gameengine/Ketsji/KX_Scene.cpp

I was reviewing a bit the code and I changed few things.
1. Previously, in some scenes, when taa_tot_samples was not set to 0, there were some small artifacts/pixels moving, then I choosed to force this setting at ge start. It seems that now we can keep viewport taa_tot_samples setting.
It has several advantages:
- The image looks more like in the viewport.
- When taa_tot_samples was set to 0, there were some weird behaviours sometimes (on a pine tree for example, the spikes were more and more thick when the image was not moving)
- The more we were waiting on a static image, the more the framerate was slowing whereas now, the GPU seems to reduce its activity when we reach tot_samples.
2. I noticed that some parts of the drawing code were called whereas it seems not needed with bge render …

UPBGE: Few tweaks

---

release/scripts/startup/bl_ui/properties_game.py
source/blender/makesrna/intern/rna_object_force.c
source/gameengine/Physics/Bullet/CcdPhysicsController.cpp

We use type VF_DD now to avoid crashes with objects like Suzanne with several separate parts.
Additionally, we recover bending distance slide option (default to 2).
2 samples:
[Softbody_simple.zip](https://github.com/UPBGE/upbge/files/5319088/Softbody_simple.zip)
[SoftBody_flag.zip](https://github.com/UPBGE/upbge/files/5319089/SoftBody_flag.zip)

UPBGE: Fix Vertex vs face soft vs soft handling collision

---

source/blender/editors/space_logic/logic_window.c
source/blender/makesdna/DNA_actuator_types.h
source/blender/makesrna/intern/rna_actuator.c
source/gameengine/Converter/BL_ConvertActuators.cpp
source/gameengine/Ketsji/KX_Scene.cpp

test file: https://pasteall.org/blend/cd5635c360c64f7f86a9502e3be82a5a
It is using ReplacePhysicsShape whereas before I think it was using ReinstancePhysicsShape.
I think it is better because it just replace the shape with an already existing shape without having to do computation.

UPBGE: ReplaceMesh Actuator: Restore replace physics shape option

---

source/blender/draw/intern/DRW_render.h
source/blender/draw/intern/draw_debug.c
source/blender/draw/intern/draw_debug.h
source/blender/draw/intern/draw_manager.c
source/blender/draw/intern/draw_manager.h
source/blender/draw/intern/draw_manager_shader.c
source/blender/editors/space_view3d/view3d_draw.c
source/blender/makesdna/DNA_scene_types.h
source/gameengine/Converter/BL_BlenderDataConversion.cpp
source/gameengine/GameLogic/SCA_GameActuator.cpp
source/gameengine/GamePlayer/GPG_Canvas.cpp
source/gameengine/GamePlayer/GPG_Canvas.h
source/gameengine/GamePlayer/GPG_ghost.cpp
source/gameengine/Ketsji/KX_BlenderCanvas.cpp
source/gameengine/Ketsji/KX_BlenderCanvas.h
source/gameengine/Ketsji/KX_BlenderMaterial.cpp
source/gameengine/Ketsji/KX_KetsjiEngine.cpp
source/gameengine/Ketsji/KX_KetsjiEngine.h
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/Launcher/LA_BlenderLauncher.cpp
source/gameengine/Launcher/LA_BlenderLauncher.h
source/gameengine/Launcher/LA_Launcher.cpp
source/gameengine/Launcher/LA_Launcher.h
source/gameengine/Launcher/LA_PlayerLauncher.cpp
source/gameengine/Launcher/LA_PlayerLauncher.h
source/gameengine/Rasterizer/RAS_ICanvas.h
source/gameengine/Rasterizer/RAS_OpenGLRasterizer/RAS_OpenGLDebugDraw.cpp

For now, I allowed only one scene because:
- Replace scene in blenderplayer viewport render generates mem leaks
- There are other few issues related to shading...
I didn't change the behaviour of viewport render in embedded.
In blenderplayer, we can use lookdev and eevee but not workbench (Because if we do nothing to change the shading type at ge start, workbench and lookdev work but not eevee...)
In blenderplayer, I hide overlays (grid, outlines...) drawing.
2D filters, ImageRender, overlay scenes, custom viewports... are not available in viewport render mode.
But stereo works and I guess virtual reality too and this is the main advantages.
Note: Why do we "need" 2 render implementations:
- Because old bge renders are done with cameras (for ImageRender, custom bge viewports, overlay …

UPBGE: Implement viewport render in blenderplayer + profile in viewport render (experimental)

---

doc/python_api/rst/bge.constraints.rst
extern/bullet2/CMakeLists.txt
extern/bullet2/patches/collision_behaviour.patch
extern/bullet2/src/BulletDynamics/ConstraintSolver/btContactSolverInfo.h
intern/rigidbody/CMakeLists.txt
release/scripts/startup/bl_ui/properties_game.py
source/blender/blenkernel/BKE_blender_version.h
source/blender/blenkernel/intern/scene.c
source/blender/blenloader/intern/versioning_280.c
source/blender/blenloader/intern/versioning_defaults.c
source/blender/blenloader/intern/versioning_upbge.c
source/blender/makesdna/DNA_scene_types.h
source/blender/makesrna/intern/rna_scene.c
source/gameengine/Ketsji/KX_PyConstraintBinding.cpp
source/gameengine/Physics/Bullet/CMakeLists.txt
source/gameengine/Physics/Bullet/CcdPhysicsEnvironment.cpp
source/gameengine/Physics/Bullet/CcdPhysicsEnvironment.h
source/gameengine/Physics/Common/PHY_IPhysicsEnvironment.h

We restore old m_erp2 value.
Thanks to @youle31 for investigating and pointing the solution. I checked the value for bullet 2.83.7 and older and it was 0.8. If you see that the behaviour is better with 1.0 with can change it to that value.
Additionally, we move back to float precision instead of double in Bullet library
Double precision is slower than float one because the float one can use SSE improvements. WE have around 5-15% better performance with float precision.
[stress_test.zip](https://github.com/UPBGE/upbge/files/5498100/stress_test.zip)
Double precision can be interesting in open world with more than 10Km from center.

UPBGE: Restore old collision behaviour

---

doc/python_api/rst/bge_types/bge.types.KX_Scene.rst
source/gameengine/Converter/BL_BlenderDataConversion.cpp
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/Ketsji/KX_Scene.h

With this new function it is possible to convert a list of objects from python:
```
i=0
ML = []
for x in range(100):
for y in range(10):
added_mesh = bpy.data.objects['Plane'].data.copy()
added_mesh.name = "Plane" + str(i)
ob = object_data_add(bpy.context, added_mesh, operator=None)
i += 1 
ML.append(ob)
ob.location = (x, y, 0)
own.scene.convertBlenderObjectsList(ML, True)
```
[Convert_objects_list_async.zip](https://github.com/UPBGE/upbge/files/5515102/Convert_objects_list_async.zip)
Also, add the possibility to choose if the conversion is asynchronous or not. For convertBlenderCollection too.
NOTE: I had to revert an improvement commit to avoid crashes. Is it ok, @youle31 ? Or we can do it in another way....

UPBGE: Convert objects list function

---

source/blender/editors/space_view3d/view3d_view.c

Fixes a build problem caused by missing preprocessor directive `WITH_XR_OPENXR` in view3d_view.c.

Fix build problem regarding missing WITH_XR_OPENXR

---

source/gameengine/Converter/BL_BlenderDataConversion.cpp
source/gameengine/Ketsji/KX_GameObject.cpp
source/gameengine/Ketsji/KX_GameObject.h
source/gameengine/Ketsji/KX_Scene.cpp

convertBlenderObject() function didn't tag the gameobject as a replica object. As only replica blenderObjects are freed, when we were calling endObject() for a converted object during runtime, the blenderObject was not freed.
This patch is an attempt to fix this issue.
I had to deal with other specificities related to objects converted during runtime and this result with something a bit experimental.
This is the reason why before merge, it would be nice if you @BluePrintRandom , @mysticfall , @lordloki could test it with your files using convertBlenderObject/convertBlenderCollection/convertObjectList and tell me if it works for you, when you will have a moment to test.
Also don't hesitate if you have remarks about the code.
Thanks!

UPBGE: Fix endObject() didn't free blenderObject for converted objects during runtime

---

source/blender/blenkernel/intern/python_component.c

I wish I knew enough C/C++ to auto-generate the list from the source files, but at least now we can register components without resorting to such an ugly hack like this:
```python
try:
from bge.types import KX_GameObject
except ImportError:
KX_GameObject = None
```

Fixes #1240: Add fake types for bge.types.*

---

source/blender/windowmanager/intern/wm_window.c
source/gameengine/BlenderRoutines/BL_KetsjiEmbedStart.cpp
source/gameengine/GamePlayer/GPG_ghost.cpp
source/gameengine/Ketsji/KX_BlenderMaterial.cpp
source/gameengine/Ketsji/KX_KetsjiEngine.cpp
source/gameengine/Ketsji/KX_KetsjiEngine.h
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/Ketsji/KX_Scene.h
source/gameengine/Launcher/LA_BlenderLauncher.cpp
source/gameengine/Launcher/LA_BlenderLauncher.h
source/gameengine/Launcher/LA_Launcher.cpp
source/gameengine/Launcher/LA_Launcher.h
source/gameengine/Launcher/LA_PlayerLauncher.cpp
source/gameengine/Launcher/LA_PlayerLauncher.h
source/gameengine/Rasterizer/RAS_OpenGLRasterizer/RAS_OpenGLDebugDraw.cpp

it contains several changes:
- Make useViewportRender option persistent during the whole runtime
(because changing of mode when we load another scene or another .blend
can disturb the pipeline) (both embedded and blenderplayer)
- Make shading type persistent during the whole runtime (both embedded and blenderplayer). I think it's better as default and if people want to change shading type they can do it with bpy during runtime.
- We call ED_area_tag_redraw for all ScrAreas when we change .blend to avoid to have not drawn (black) areas and also at game engine exit to refresh the screen. For now, I didn't notice the need to redraw areas when we change scene (only when we change .blend)
- To limit memory leaks count when we change .blend, we use BKE_screen_exit which does a good enough …

UPBGE: Allow to change .blend in embedded in "viewport render mode"

---

source/blender/blenkernel/BKE_python_component.h
source/blender/blenkernel/BKE_sca.h
source/blender/blenkernel/intern/object.c
source/blender/blenkernel/intern/python_component.c
source/blender/blenkernel/intern/sca.c
source/blender/makesdna/DNA_python_component_types.h
source/blender/makesrna/intern/rna_python_component.c

This commit adds support for Python component properties which can accept Blender data types like Mesh or Object as their values. In short, now you can do something like this:
In order to declare an `ID` type property, you can initialise the component `args` property with a proper type object like this:
```python
class Bootstrap(KX_PythonComponent):
args = OrderedDict((
("key", "alleycat"),
("config", "//config.json"),
("Action", bpy.types.Action),
("Armature", bpy.types.Armature),
("Camera", bpy.types.Camera),
("Collection", bpy.types.Collection),
("Curve", bpy.types.Curve),
("Image", bpy.types.Image),
("Key", bpy.types.Key),
("Library", bpy.types.Library),
("Light", bpy.types.Light),
("Material", bpy.types.Material),
("Mesh", bpy.types.Mesh),
("Movie Clip", bpy.types.MovieClip),
("Node …
```

Support data (ID) type properties for Python components

---

doc/python_api/rst/bge_types/bge.types.KX_Scene.rst
source/gameengine/Converter/BL_BlenderDataConversion.cpp
source/gameengine/Converter/BL_BlenderSceneConverter.cpp
source/gameengine/Converter/BL_BlenderSceneConverter.h
source/gameengine/Ketsji/KX_GameObject.cpp
source/gameengine/Ketsji/KX_KetsjiEngine.cpp
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/Ketsji/KX_Scene.h

It is because pacyfist had issues with this.
I tested with these files for now:
- Simple case:
[GetGameObjectFromObject.zip](https://github.com/UPBGE/upbge/files/5768504/GetGameObjectFromObject.zip)
- getGameObject for replicas objects:
[GetGameObjectFromObjectReplicas.zip](https://github.com/UPBGE/upbge/files/5768507/GetGameObjectFromObjectReplicas.zip)
- Launcher1 (append a cube, convert to gameobj, and see if it is working):
[launcher.zip](https://github.com/UPBGE/upbge/files/5768510/launcher.zip)
- Launcher2 (append several cubes and see):
[launcher2.zip](https://github.com/UPBGE/upbge/files/5768519/launcher2.zip)
- The cube to append:
[cube.zip](https://github.com/UPBGE/upbge/files/5768522/cube.zip)
It seems to work fine in embedded but not in blenderplayer. I need to figure out why.

UPBGE: Try to add an helper to get KX_GameObject from Object

---

source/gameengine/Ketsji/KX_PythonComponentManager.cpp
source/gameengine/Ketsji/KX_PythonComponentManager.h
source/gameengine/SceneGraph/SG_Node.cpp
source/gameengine/SceneGraph/SG_Node.h

This PR intends to change the invocation order of `KX_PythonComponent` so that a component on a game object would get invoked before those attached to its ancestors.
Consider a case where a Python component `P` requires other components `C1` and `C2` as its dependency. We can imagine they are attached in a game object tree which looks like below:
```
P -*- C1
|
*- C2
```
As a component is often initialised from arguments given in its `start(args)` callback, `C1` and `C2` may still remain in an invalid state when `P`'s `start` method gets called, because UPBGE currently does not guaranteed the invocation order in such cases.
Apparently, the engine invokes game objects in an alphabetical order of their names regardless of their respective depth which is not a very useful behaviour, IMO.
In …

Ensure Python components of a game object started before those on its ancestors

---

source/gameengine/GamePlayer/GPG_ghost.cpp

Addons need to read userpref.blend file to know which addons are
registered.
It allows to use registered addons in blendeprlayer.
If no userpref.blend is found, default user preferences are
loaded.
Code picked from wm_files > wm_homefile_read

UPBGE: Use userprefs to load addons in blenderplayer

---

source/gameengine/Converter/BL_BlenderDataConversion.cpp
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/Ketsji/KX_Scene.h

It removes the spawnlist related code as it is not necessary and avoids right behaviour for instance collection.
Thanks to @youle31 for the solution and tests.
I tested with a lot blends to be sure (instance_collection at start, collection spawn and object spawn)
[collection_instance_spawn_modified.zip](https://github.com/UPBGE/upbge/files/5900706/collection_instance_spawn_modified.zip)
[DupliGroupRecurssive.zip](https://github.com/UPBGE/upbge/files/5900707/DupliGroupRecurssive.zip)
[Instanced-collection-from-OBy1.zip](https://github.com/UPBGE/upbge/files/5900708/Instanced-collection-from-OBy1.zip)
[InstanceTest2.zip](https://github.com/UPBGE/upbge/files/5900709/InstanceTest2.zip)
[spawn_collection.zip](https://github.com/UPBGE/upbge/files/5900710/spawn_collection.zip)

UPBGE: Fix collection instance spawning

---

source/gameengine/Common/CM_Clock.cpp
source/gameengine/Common/CM_Clock.h
source/gameengine/Common/CMakeLists.txt
source/gameengine/Ketsji/KX_KetsjiEngine.cpp
source/gameengine/Ketsji/KX_KetsjiEngine.h
source/gameengine/Ketsji/KX_TimeCategoryLogger.cpp
source/gameengine/Ketsji/KX_TimeCategoryLogger.h

Several users said that they prefered time management as in 0.2.4.
Then I recovered panzergame Time management refactor:
Mainly this:
e9b07807f99d97dde7162b3fbb7439ea70fea0b5
+ that:
dfb83b57e0ca5f4451122e3eadc732f9a784df37

UPBGE: Recover panzergame Time refactor (without std::sleep_for)

---

source/blender/editors/space_logic/logic_window.c

This way the state number and the controller type can be read again.
Now, the controller is displayed this way:
With the changes a new row is introduced to get more space and to can reordering the UI elements. This way the controller type and the state can be read again.
Additionally, the controller column is increased a bit to be in line with sensor & actuator columns.

UPBGE: Increase the width size of controller brick and reordering

---

source/gameengine/Physics/Bullet/CcdPhysicsController.cpp

I don't know what it means but it is just to not have the softbody
inactive when we uncheck CCD_BSB_SHAPE_MATCHING (Shape Match -
use_shape_match) option.
EDIT: In 2.79 official, the simulation was running when we unchecked Shape Match, not in upbge 0.2.5

UPBGE: Enable support of SoftBody volumes (when we uncheck Shape Match)

---

source/gameengine/VideoTexture/VideoFFmpeg.cpp

This way we can capture high resolutions (e.g. 1920x1080 at 30fps) from Camera under Windows.

UPBGE: Use the up-to-date dshow format instead of death vfwcap format

---

doc/python_api/rst/bge.texture.rst
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/VideoTexture/ImageRender.cpp
source/gameengine/VideoTexture/ImageRender.h

With recent custom bge loop refactor, it was not possible anymore to set evaluated scene render options before ImageRender pass.
It can be interesting to set these options:
- It is better to use evaluated scene before when we set the render options because the depsgraph is not notified to do an extra draw pass for no reason.
- We might want to set background transparent or disable post processing effects before ImageRender pass.
To make this possible again, pre_draw callbacks are implemented and inserted after BKE_scene_graph_update_tagged and before the image render bge draw loop.
I have no usecase for post_draw callbacks yet but it costs nothing to add it.
Test file: https://ufile.io/kx28163c
Python API:
Side note:
ImageRender often requires to hide some objects before the ImageRender …

UPBGE: ImageRender pre/post draw callbacks

---

source/gameengine/Converter/BL_BlenderDataConversion.cpp
source/gameengine/Physics/Bullet/CcdPhysicsController.cpp
source/gameengine/Physics/Bullet/CcdPhysicsController.h
source/gameengine/Physics/Bullet/CcdPhysicsEnvironment.cpp

- It recovers something in BlenderDataConversion to take into account compound children. My guess is that as I didn't know what was compound, I disabled it during 0.3 development.
- It recovers a commit just after 0.2.2: 067da32bf00a0917f2deceb7dbe8e88ef6f6f9a1 (I saw you already had recovered another previous commit related to compound just before 0.2.2)
wuaeio told me that it was not working then I did that. He tested and told me that it was working as excpected according to him.
I saw you already pushed a commit related to compound a long time ago in official bge, then maybe you know what it is and can evaluate better than me if it sounds ok to you.
parenthesis: I left dm argument in physenv->ConvertObject(...., DerivedMesh *dm, ....) but it is always nullpr.

UPBGE: Try to recover 0.2.5 behaviour for compound things

---

source/gameengine/Ketsji/BL_Action.cpp

it is an attempt to fix https://github.com/UPBGE/upbge/issues/1445
There are 2 things:
- We compare directly action pointers instead of action names when we can.
- When it is not possible, for currently playable action "data types", we ensure that m_action (actuator's action) FCurve rna path contains the "data name" (constraint name, modifier name...) (if not the action is not played). The code is derived from BKE_modifier_uses_time and adapted.
BL_Action code can potentially be improved to support more action types but needs more investigations and can be done later.

UPBGE: BL_Action: Add checks to try to ensure we're playing the right action

---

source/gameengine/Ketsji/KX_Scene.cpp

https://github.com/UPBGE/upbge/issues/1470
I think we need to call UpdateParent after animations transform are flushed with BKE_scene_graph_update_tagged.

UPBGE: Try to fix parent transform issues with animations

---

source/gameengine/Ketsji/BL_Action.cpp
source/gameengine/Ketsji/KX_FontObject.cpp
source/gameengine/Ketsji/KX_GameObject.cpp
source/gameengine/Ketsji/KX_GameObject.h
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/Ketsji/KX_Scene.h
source/gameengine/VideoTexture/ImageRender.cpp

There are remaining cases not handled (ImageRender + few other cases)... It would need to find a system for all occurrences of DEG_id_tag_update in ge code.
But I think it is fixing most of common cases. Maybe there is a simpler/better way than this patch to proceed.
It is to fix this: https://github.com/UPBGE/upbge/issues/1481 and other potential issues with extra render passes...

UPBGE: Fix most of missing depsgraph notifiers for extra render passes

---

source/gameengine/Converter/BL_ConvertProperties.cpp

Instead of passing an empty string for String property creation we pass the stream data.
Additionally, we remove the stream fail check as the conversion is well done but we mantain the bad check to check the stream integrity. This way we avoid the console error message that it is not very useful for the user (as the conversion is really done).
Previously, the console error message was visible when we use, for example, a font with the text "hello" but we set the string property as integer.

UPBGE: improve text properties conversion

---

source/blender/blenkernel/BKE_python_component.h
source/blender/blenkernel/intern/python_component.c
source/blender/editors/space_logic/logic_ops.c
source/blender/makesrna/intern/rna_object.c
source/blender/makesrna/intern/rna_python_component.c

This will allow overriding the properties of a `KX_PythonComponent` which is attached to an object linked as a library.
However, it doesn't make components themselves overridable, or other properties of `GameObjectSettings` like sensors or actuators for that matter. I tried to make it work but haven't been successful so far.
If anyone has an idea what could be missing to make it work, please let me know. Thanks!

Make PythonComponent's properties overridable

---

CMakeLists.txt
build_files/cmake/platform/platform_win32.cmake
release/license/BSD-3-Clause-license-BCompat7.txt
source/blenderplayer/CMakeLists.txt
source/creator/CMakeLists.txt

This adds Windows 7 support to UPBGE as it had before.
Adapting the work of @nalexandru at https://github.com/nalexandru/BlenderCompat
Kudos to him to fix the issue.
Edit: the libraries to be included under lib directory are in this link: https://mega.nz/file/t8dAQJLb#kz_D0SlhWcfH00UQw5RZ_zyEkA3-4Escg-BX2cLplHo

UPBGE: Windows 7 support for UPBGE

---

source/blender/blenkernel/intern/sca.c
source/gameengine/BlenderRoutines/BL_KetsjiEmbedStart.cpp
source/gameengine/Ketsji/KX_PythonInit.cpp
source/gameengine/Ketsji/KX_PythonInit.h

- Use the host window manager's keyconfs so that the embedded one won't create new keymaps which will get overwritten over the global operators and freed after the game ends otherwise, which may lead to a crash.
- Use BPY_python_reset(C) when switching filres in embedded to ensure right bpy context
- Comment problematic code when loading new .blend (it was the piece of code added to append python controller modules scripts in the same time than an Object. This code is disabled, but could be enabled again if we find a way to avoid to call it just when we are reading/loading the new .blend EDIT: It was crashing in ledi.blend after restarting several times in visual studio 2019 on windows in embedded in debug build)
test files:
[restart-load.zip](https://github.com/UPBGE/upbge/files/6941101/r …

UPBGE: Fix few issues related to .blend loading/restart during runtime

---

source/gameengine/Ketsji/KX_PythonComponent.cpp
source/gameengine/Ketsji/KX_PythonProxy.cpp
source/gameengine/Ketsji/KX_PythonProxy.h

Fix a crash due to negative ref count upon replicating a Python proxy. Only reproducible with a debug build of Python.

Fix a crash due to negative refcount when replicating a Python proxy

---

.github/workflows/publish-api-and-stubs.yml

This Github workflow generates and publishes API documentation and stubs to [UPBGE/UPBGE-API](https://github.com/UPBGE/UPBGE-API) and [PyPI repository](https://pypi.org/manage/project/upbge-stubs) respectively, whenever the master branch is updated.

Add workflow to publish API docs and stubs

---

source/blender/blenkernel/intern/python_proxy.c

This PR eliminates the following warning message occurning while compiling `python_proxy.c`:
```
warning: initialization of ‘long int’ from ‘void *’ makes integer from pointer without a cast NULL
```
`FakeType` defines a structure to create a new Python type from the native side. And according to the [relevant documentation](https://docs.python.org/3/c-api/typeobj.html), the problematic slot used to be `tp_print` which expected a function pointer (for which `NULL` is a legal value).
However, it looks like they changed it to `tp_vectorall_offset` which expects `Py_ssize_t` that translates to `int` or `long` depending on the target platform.
And because `NULL` is defined as `((void *)0)` in C, so it's not a valid value for non-pointer type such as `long`.

Fix wrong init value for tp_vectorall_offset

---

source/gameengine/Device/DEV_Joystick.cpp

There is no need to maintain this system as we compile with SDL 2.0+ statically always. Additionally, to comment that this system was done during the transition between SDL 1.2 to SDL 2.0. Now this transition is more than over.

UPBGE: SDL Check macro removal

---

source/gameengine/Expressions/intern/PyObjectPlus.cpp
source/gameengine/Ketsji/KX_PythonInit.cpp

This change will fix build errors on Python 3.10 caused by using its internal API (i.e. functions prefixed by `_`).
List below are issues dealing with similar problems:
* https://developer.blender.org/T85573
* https://bugzilla.redhat.com/show_bug.cgi?id=1912903

Fix build problem with Python 3.10 due to internal API references

---

source/blender/blenkernel/intern/python_proxy.c

This fixes the problem of KX_GameObject subtypes (e.g. KX_Camera) not being recognised as a valid base class for a custom game object.
How to reproduce the error
------------------------------------
* Write a custom class that inherits `KX_Camera`
* Select a camera object and open the _Game Object_ panel.
* Choose _Select_ and try to assign the custom class.
Prior to this patch, it will fail with an error message saying the provide class is not a valid subtype of `KX_GameObject`.

Add base type info to 'fake' BGE type definitions

---

source/gameengine/Ketsji/KX_PythonInit.cpp

Due to a change of behaviour in Python 3.10, running a game in embedded mode once will now make Blender lose all system module paths like `/scripts/modules`, resulting in various problems.
Before 3.10, `Py_InitializeFromConfig` preserved `sys.path`, so backing up the environment after that point didn't cause much of a problem.
However, the behaviour seems to have changed in 3.10 (I couldn't find any reference in documentation or changelog, though) which results in loss of system module paths such as `scripts/modules` after running the game once in embedded mode.
This PR tries to fix the problem by taking a back before `Py_InitializeFromConfig` so that it can be correctly restored after the game finishes.
How to reproduce:
* Launch UPBGE compiled with Python 3.10.
* Open scripting console …

Fix module path problem on Python 3.10

---

source/blender/blenkernel/BKE_global.h
source/blender/editors/undo/memfile_undo.c
source/gameengine/BlenderRoutines/BL_KetsjiEmbedStart.cpp

I used a new Global ... idk if it is good

UPBGE: Use old undo only at bge exit but new undo in viewport

---

.github/workflows/publish-api-and-stubs.yml

This should restore the missing documentation with `aud` module.

Fix problem with numpy error while building API doc

---

source/blender/draw/intern/draw_manager.c

After last changes in curves, volumetrics and smoke we have to add new DRW initialization for these elements.
Curves initializes and update the hair methods now.
I have some doubts with DRW_globals_update() to update UBO's. This function was out of our DRW_game_render_loop function due to any specific reason?
I tested with a few files and they worked well.
[volumetric_crash.zip](https://github.com/UPBGE/upbge/files/8586684/volumetric_crash.zip)

UPBGE: Fixing crash using volumetrics

---

.github/workflows/publish-api-and-stubs.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

source/gameengine/VideoTexture/VideoFFmpeg.h

This fixes the building problem due to a missing include statement of `avcodec.h`.
I'm not entirely sure why it's only happening when building UPBGE on Linux with system dependencies or if it's the correct way to address the problem.
But it looks to solve the issue on my end so I'd appreciate if someone more knowledgeable (reads, either youle or ExxiL 😉) could verify the change.
Thanks!

Fix compile problem due to missing avcodec header

---

source/blender/editors/space_logic/logic_ops.c

There were reports here: https://github.com/UPBGE/upbge/issues/1718 and on discord about Bricky Nodes addon crashes.
I saw it was related to changes I did in logic_ops related to undo (to use old undo for logic operators).
It seems this code avoids some crashes, even if I don't know exactly what happens internally.
IzaZed and arch-sketch tested and confirmed it was better after this patch.

UPBGE: Attempt to fix issues with Bricky Nodes

---

doc/python_api/examples/bge.texture.2.py
doc/python_api/examples/bpy.types.Operator.py
doc/python_api/examples/bpy.types.USDHook.py
doc/python_api/examples/mathutils.Matrix.py
doc/python_api/rst/bge.constraints.rst
doc/python_api/rst/bge.logic.rst
doc/python_api/rst/bge.render.rst
doc/python_api/rst/bge.texture.rst
doc/python_api/rst/bge_types/bge.types.BL_ArmatureObject.rst
doc/python_api/rst/bge_types/bge.types.EXP_ListValue.rst
doc/python_api/rst/bge_types/bge.types.KX_2DFilter.rst
doc/python_api/rst/bge_types/bge.types.KX_ConstraintWrapper.rst
doc/python_api/rst/bge_types/bge.types.KX_GameObject.rst
doc/python_api/rst/bge_types/bge.types.KX_MeshProxy.rst
doc/python_api/rst/bge_types/bge.types.SCA_DelaySensor.rst
doc/python_api/rst/bge_types/bge.types.SCA_ISensor.rst
doc/python_api/rst/bge_types/bge.types.SCA_JoystickSensor.rst
doc/python_api/rst/bge_types/bge.types.SCA_MouseFocusSensor.rst
doc/python_api/rst/bge_types/bge.types.SCA_MouseSensor.rst
doc/python_api/rst/bge_types/bge.types.SCA_PythonController.rst
doc/python_api/rst/bge_types/bge.types.SCA_PythonJoystick.rst
doc/python_api/rst/bge_types/bge.types.SCA_RandomActuator.rst
doc/python_api/rst/bgui/widget.rst
doc/python_api/sphinx_changelog_gen.py

Found via `codespell -q 3 -S "*.diff,*.po,./AUTHORS,./extern" -L aci,alo,ans,bu,buildt,childs,ccompiler,clen,datas,dependees,eiter,espace,fiter,fpt,inout,inouts,lod,mata,mis,mot,nd,numer,ot,parm,parms,pinter,pixelx,poin,re-use,seh,te,thi,toi,ue`
Any chance this can be merged on projects.blender.org ?

Fix typos in doc/ subdirectory

---

scripts/bge/interpreter.py

Missing shortcut to quit terminal on OSX. This PR is to add the shortcut to improve the experience for Mac users.

Add OSX shortcut to quit the python interpreter.

---

doc/python_api/rst/bge_types/bge.types.KX_2DFilterFrameBuffer.rst
source/gameengine/Ketsji/KX_2DFilterFrameBuffer.cpp
source/gameengine/Ketsji/KX_2DFilterFrameBuffer.h
source/gameengine/Rasterizer/RAS_2DFilterFrameBuffer.cpp
source/gameengine/Rasterizer/RAS_2DFilterFrameBuffer.h

This feature allows `KX_FilterFrameBuffer` to provide a `GPUTexture` object when added as offscreen buffer. This texture can then be used in other shaders and the gpu module draw calls.
Usage:
```python
filter = bge.logic.getCurrentScene().filterManager.addFilter(0, 12, glsl)
filter.addOffScreen(0)
```
and then to get the texture (and use it as `uniform sampler custom_framebuffer` in glsl):
```python
texture_object = filter.offScreen.getColorTexture()
shader = GPUShader(...., ....)
shader.uniform_sampler('custom_framebuffer', texture_object)
```
Test File:
[Test04.zip](https://github.com/UPBGE/upbge/files/14284286/Test04.zip)

add GetColorTexture and GetDepthTexture to KX_FilterFrameBuffer

---

source/creator/CMakeLists.txt

Fix an invalid reference of a metainfo.xml file (changed by df563ed):
```
CMake Error at source/creator/cmake_install.cmake:270 (file):
file INSTALL cannot find
"/home/mysticfall/.cache/yay/upbge-git/src/upbge/release/freedesktop/org.blender.Blender.metainfo.xml":
No such file or directory.
Call Stack (most recent call first):
cmake_install.cmake:51 (include)
make: *** [Makefile:130: install] 오류 1
```

Fix build problem due to missing metainfo.xml file

---

source/gameengine/Ketsji/KX_PythonInit.cpp

Build was failing due to compile errors on macOS. It was trying to call strchr on py_path_bundle, but py_path_bundle was not a C string

Fix build on Apple devices: `py_path_bundle` is not a C string

---

source/blender/makesdna/DNA_modifier_defaults.h
source/blender/makesdna/DNA_modifier_types.h
source/blender/makesdna/intern/dna_defaults.c
source/blender/modifiers/CMakeLists.txt
source/blender/modifiers/MOD_modifiertypes.hh
source/blender/modifiers/intern/MOD_deform_bge.cc
source/blender/modifiers/intern/MOD_util.cc
source/gameengine/Ketsji/KX_GameObject.cpp
source/gameengine/Physics/Bullet/CcdPhysicsController.cpp
source/gameengine/Physics/Bullet/CcdPhysicsController.h
source/gameengine/Physics/Common/PHY_IPhysicsController.h

It creates a simple basic OnlyDeform modifier.
This PR has several goals:
- Create an unique deformed shape for softbodies which have several mesh users
- Avoid deforming original mesh as it creates issues for example on scene restart
- Attempt to fix some transform issues (We still need to Apply Scale before bge start)
It doesn't solve all issues but I think it is a progress.
It has been tested with some of my files:
[Nouveau dossier.zip](https://github.com/user-attachments/files/20730340/Nouveau.dossier.zip)

UPBGE: Add a modifier for softbodies

---

release/freedesktop/org.upbge.UPBGE.metainfo.xml

This pull request expands the Freedesktop metadata with additional information. Further, it also adds the v0.44 release notes- as expected by platforms such as Flathub.
Please make sure to add the appropriate release notes to this file on the next major release. Alternatively, let me know when you're ready to create the tag, and I'll do it myself.

Additional Freedesktop metadata changes, along with v0.44 release notes

---

doc/python_api/rst/bge_types/bge.types.KX_2DFilter.rst
source/gameengine/Rasterizer/RAS_2DFilter.cpp
source/gameengine/Rasterizer/RAS_OpenGLFilters/RAS_Blur2DFilter.glsl
source/gameengine/Rasterizer/RAS_OpenGLFilters/RAS_Dilation2DFilter.glsl
source/gameengine/Rasterizer/RAS_OpenGLFilters/RAS_Erosion2DFilter.glsl
source/gameengine/Rasterizer/RAS_OpenGLFilters/RAS_Laplacian2DFilter.glsl
source/gameengine/Rasterizer/RAS_OpenGLFilters/RAS_Prewitt2DFilter.glsl
source/gameengine/Rasterizer/RAS_OpenGLFilters/RAS_Sharpen2DFilter.glsl
source/gameengine/Rasterizer/RAS_OpenGLFilters/RAS_Sobel2DFilter.glsl
source/gameengine/Rasterizer/RAS_Shader.cpp
source/gameengine/Rasterizer/RAS_Shader.h

This PR improves the GLSL uniform parser in RAS_Shader::GetParsedProgram with the following changes:
•	Ignores user-declared uniforms for bgl_RenderedTexture and bgl_DepthTexture to avoid redeclaration errors (these are now handled internally).
•	Handles uniform arrays and multiple variable declarations on a single line (e.g. uniform float a, b[4], c;).
•	For each user uniform, registers a push constant (except for built-in ones).
•	Replaces legacy built-in variables in shader code:
•	bgl_TextureCoordinateOffset[...] → g_data.coo_offset[...]
•	bgl_RenderedTextureWidth → g_data.width
•	bgl_RenderedTextureHeight → g_data.height
•	Comments out all user uniform declarations in the final shader code to prevent GLSL errors.
•	The parser is robust to extra spaces and tabs between keywords, …

UPBGE: Improve GLSL uniform parser and replace legacy built-in variables with UBO access

---

release/datafiles/userdef/userdef_default.c
source/blender/blenkernel/BKE_blender_version.h
source/blender/blenkernel/intern/blendfile.cc
source/blender/blenloader/intern/versioning_upbge.cc
source/blender/blenloader/intern/versioning_userdef.cc
source/blender/makesdna/DNA_userdef_types.h

We adopt the same system as in Blender to select the default UPBGE addons.
Currently, I have selected Logic nodes, Bricky nodes and Save as Runtime addons. 
We can discuss later if we add some additional ones.

UPBGE: Add default UPBGE addons

---

source/blenderplayer/CMakeLists.txt
source/gameengine/Converter/BL_ConvertControllers.cpp
source/gameengine/Ketsji/KX_GameObject.h
source/gameengine/Ketsji/KX_KetsjiEngine.cpp
source/gameengine/Ketsji/KX_LodManager.h
source/gameengine/Ketsji/KX_PythonInit.cpp
source/gameengine/Ketsji/KX_Scene.cpp
source/gameengine/Physics/Common/PHY_IPhysicsEnvironment.h
source/gameengine/Rasterizer/RAS_Shader.h
source/gameengine/VideoTexture/blendVideoTex.cpp

Fix user-facing and non-user-facing typos  
Found via `codespell -D ../dictionary.txt -S "./locale,./intern,./extern" -L eiter,fiter,fpt,infront,inout,ot,parm,parms,poin,ptd,te source/gameengine/`

Fix various typos
